import { Ionicons } from '@expo/vector-icons';
import { type Href, router, useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppButton } from '@/components/ui/AppButton';
import { AppInput } from '@/components/ui/AppInput';
import { Colors, FontFamily, Radius, Shadow } from '@/constants/theme';
import { useAuth } from '@/contexts/AuthContext';
import { getApiErrorMessage } from '@/utils/apiError';

export default function LoginScreen(){const{returnTo}=useLocalSearchParams<{returnTo?:string}>();const{login}=useAuth();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[showPassword,setShowPassword]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
  const submit=async()=>{if(!/^\S+@\S+\.\S+$/.test(email.trim())||!password){setError('Vui lòng nhập đúng email và mật khẩu.');return}setLoading(true);setError('');try{await login({email:email.trim().toLowerCase(),password});router.replace((returnTo||'/') as Href)}catch(cause){setError(getApiErrorMessage(cause,'Đăng nhập không thành công.'))}finally{setLoading(false)}};
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Pressable style={styles.close} onPress={()=>router.canGoBack()?router.back():router.replace('/')}><Ionicons name="close" size={23} color={Colors.text}/></Pressable><View style={styles.brandWrap}><View style={styles.mark}><Text style={styles.markText}>L</Text></View><Text style={styles.brand}>LUMÉ</Text><Text style={styles.tagline}>ÁO DÀI & CHỤP ẢNH</Text></View><View style={styles.card}><Text style={styles.eyebrow}>CHÀO MỪNG TRỞ LẠI</Text><Text style={styles.title}>Đăng nhập</Text><Text style={styles.subtitle}>Đăng nhập để giữ lịch, thanh toán và theo dõi đơn hàng của bạn.</Text><AppInput label="Địa chỉ email" value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/><View><AppInput label="Mật khẩu" value={password} onChangeText={setPassword} secureTextEntry={!showPassword} onSubmitEditing={()=>void submit()} returnKeyType="done"/><Pressable style={styles.eye} onPress={()=>setShowPassword(value=>!value)}><Ionicons name={showPassword?'eye-off-outline':'eye-outline'} size={19} color={Colors.textMuted}/></Pressable></View><Pressable onPress={()=>router.push('/(auth)/forgot-password' as Href)}><Text style={styles.forgot}>Quên mật khẩu?</Text></Pressable>{!!error&&<View style={styles.error}><Ionicons name="alert-circle" size={16} color={Colors.error}/><Text style={styles.errorText}>{error}</Text></View>}<AppButton title="Đăng nhập" loading={loading} onPress={()=>void submit()}/><View style={styles.signupRow}><Text style={styles.help}>Chưa có tài khoản?</Text><Pressable onPress={()=>router.push({pathname:'/(auth)/register',params:{returnTo}} as unknown as Href)}><Text style={styles.signup}>Đăng ký ngay</Text></Pressable></View><Pressable onPress={()=>router.push('/(auth)/verify-email' as Href)}><Text style={styles.verify}>Đã đăng ký nhưng chưa xác minh email?</Text></Pressable></View></ScrollView></KeyboardAvoidingView></SafeAreaView>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{flexGrow:1,padding:20,justifyContent:'center'},close:{position:'absolute',top:14,left:16,width:40,height:40,borderRadius:99,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface,alignItems:'center',justifyContent:'center'},brandWrap:{alignItems:'center',marginBottom:28},mark:{width:54,height:54,borderRadius:99,backgroundColor:Colors.primary,alignItems:'center',justifyContent:'center'},markText:{fontFamily:FontFamily.display,fontSize:22,color:Colors.white},brand:{fontFamily:FontFamily.display,fontSize:24,letterSpacing:6,color:Colors.primary,marginTop:12},tagline:{fontFamily:FontFamily.bodyMedium,fontSize:9,letterSpacing:1.5,color:Colors.textMuted,marginTop:3},card:{width:'100%',maxWidth:480,alignSelf:'center',backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.xl,padding:20,gap:15,...Shadow},eyebrow:{fontFamily:FontFamily.bodyBold,fontSize:9,color:Colors.primary},title:{fontFamily:FontFamily.display,fontSize:30,color:Colors.text,marginTop:-6},subtitle:{fontFamily:FontFamily.body,fontSize:11,lineHeight:18,color:Colors.textSecondary,marginTop:-7,marginBottom:4},eye:{position:'absolute',right:13,top:33,width:34,height:42,alignItems:'center',justifyContent:'center'},forgot:{fontFamily:FontFamily.bodySemiBold,fontSize:10,color:Colors.primary,textAlign:'right',marginTop:-8},error:{flexDirection:'row',alignItems:'center',gap:7,padding:10,borderRadius:Radius.sm,backgroundColor:Colors.errorSoft},errorText:{flex:1,fontFamily:FontFamily.bodyMedium,fontSize:10,color:Colors.error},signupRow:{flexDirection:'row',alignItems:'center',justifyContent:'center',gap:5},help:{fontFamily:FontFamily.body,fontSize:9,lineHeight:15,color:Colors.textMuted,textAlign:'center'},signup:{fontFamily:FontFamily.bodyBold,fontSize:10,color:Colors.primary},verify:{fontFamily:FontFamily.bodyMedium,fontSize:9,color:Colors.primary,textAlign:'center'}});
