import { type Href,router,useLocalSearchParams } from 'expo-router';
import { useState } from 'react';
import { Pressable,Text,View } from 'react-native';
import { authApi } from '@/apis/authApi';
import { AuthFrame,authStyles as s } from '@/components/auth/AuthFrame';
import { AppButton } from '@/components/ui/AppButton';
import { AppInput } from '@/components/ui/AppInput';
import { Colors,FontFamily } from '@/constants/theme';
import { getApiErrorMessage } from '@/utils/apiError';

export default function Register(){const{returnTo}=useLocalSearchParams<{returnTo?:string}>();const[form,setForm]=useState({fullName:'',email:'',phone:'',password:'',confirm:''});const[agreed,setAgreed]=useState(false);const[loading,setLoading]=useState(false);const[error,setError]=useState('');
  const submit=async()=>{const email=form.email.trim().toLowerCase();if(form.fullName.trim().length<3){setError('Họ tên phải có ít nhất 3 ký tự.');return}if(!/^\S+@\S+\.\S+$/.test(email)){setError('Email không đúng định dạng.');return}if(!/^[0-9+\-\s()]{8,20}$/.test(form.phone.trim())){setError('Số điện thoại không hợp lệ.');return}if(form.password.length<8||!/[A-Za-z]/.test(form.password)||!/[0-9]/.test(form.password)){setError('Mật khẩu cần ít nhất 8 ký tự, gồm chữ và số.');return}if(form.password!==form.confirm){setError('Mật khẩu xác nhận không trùng khớp.');return}if(!agreed){setError('Bạn cần đồng ý với điều khoản sử dụng.');return}setLoading(true);setError('');try{const result=await authApi.register({fullName:form.fullName.trim(),email,phone:form.phone.trim(),password:form.password});router.replace({pathname:'/(auth)/verify-email',params:{email,otp:result.demoOtp??'',returnTo}} as unknown as Href)}catch(e){setError(getApiErrorMessage(e,'Không thể đăng ký tài khoản.'))}finally{setLoading(false)}};
  return <AuthFrame><View style={s.card}><Text style={s.eyebrow}>THAM GIA LUMÉ</Text><Text style={s.title}>Tạo tài khoản mới</Text><Text style={s.subtitle}>Đăng ký tài khoản khách hàng để thuê áo dài và đặt lịch chụp ảnh.</Text><AppInput label="Họ và tên" value={form.fullName} onChangeText={v=>setForm(f=>({...f,fullName:v}))}/><AppInput label="Địa chỉ email" value={form.email} onChangeText={v=>setForm(f=>({...f,email:v}))} autoCapitalize="none" keyboardType="email-address"/><AppInput label="Số điện thoại" value={form.phone} onChangeText={v=>setForm(f=>({...f,phone:v}))} keyboardType="phone-pad"/><AppInput label="Mật khẩu" value={form.password} onChangeText={v=>setForm(f=>({...f,password:v}))} secureTextEntry hint="Tối thiểu 8 ký tự, gồm chữ và số."/><AppInput label="Xác nhận mật khẩu" value={form.confirm} onChangeText={v=>setForm(f=>({...f,confirm:v}))} secureTextEntry/><Pressable onPress={()=>setAgreed(v=>!v)} style={s.row}><View style={{width:20,height:20,borderRadius:5,borderWidth:1,borderColor:agreed?Colors.primary:Colors.border,backgroundColor:agreed?Colors.primary:Colors.surface,alignItems:'center',justifyContent:'center'}}><Text style={{color:Colors.white,fontSize:12}}>{agreed?'✓':''}</Text></View><Text style={{flex:1,fontFamily:FontFamily.body,fontSize:9,lineHeight:15,color:Colors.textSecondary}}>Tôi đồng ý với điều khoản dịch vụ và chính sách bảo mật của LUMÉ.</Text></Pressable>{!!error&&<Text style={s.error}>{error}</Text>}<AppButton title="Đăng ký" loading={loading} onPress={()=>void submit()}/><View style={s.row}><Text style={s.help}>Đã có tài khoản?</Text><Pressable onPress={()=>router.replace({pathname:'/(auth)/login',params:{returnTo}} as unknown as Href)}><Text style={s.link}>Đăng nhập</Text></Pressable></View></View></AuthFrame>}
