import { type Href,router,useLocalSearchParams } from 'expo-router';
import { useEffect,useState } from 'react';
import { Pressable,Text,View } from 'react-native';
import { authApi } from '@/apis/authApi';
import { AuthFrame,authStyles as s } from '@/components/auth/AuthFrame';
import { AppButton } from '@/components/ui/AppButton';
import { AppInput } from '@/components/ui/AppInput';
import { getApiErrorMessage } from '@/utils/apiError';

export default function VerifyEmail(){const params=useLocalSearchParams<{email?:string;otp?:string;returnTo?:string}>();const[email,setEmail]=useState(params.email??'');const[otp,setOtp]=useState(params.otp??'');const[loading,setLoading]=useState(false);const[resending,setResending]=useState(false);const[cooldown,setCooldown]=useState(0);const[message,setMessage]=useState(params.otp?'Mã OTP demo đã được điền tự động.':'');const[error,setError]=useState('');useEffect(()=>{if(cooldown<=0)return;const timer=setInterval(()=>setCooldown(v=>Math.max(0,v-1)),1000);return()=>clearInterval(timer)},[cooldown]);
  const verify=async()=>{if(!/^\S+@\S+\.\S+$/.test(email.trim())||!/^[0-9]{6}$/.test(otp)){setError('Vui lòng nhập email và mã OTP gồm 6 chữ số.');return}setLoading(true);setError('');try{await authApi.verifyEmail({email:email.trim().toLowerCase(),otp});router.replace({pathname:'/(auth)/login',params:{returnTo:params.returnTo}} as unknown as Href)}catch(e){setError(getApiErrorMessage(e,'Mã OTP không hợp lệ hoặc đã hết hạn.'))}finally{setLoading(false)}};
  const resend=async()=>{if(!/^\S+@\S+\.\S+$/.test(email.trim())){setError('Vui lòng nhập đúng email trước.');return}setResending(true);setError('');try{const result=await authApi.resendVerification(email.trim().toLowerCase());if(result.demoOtp)setOtp(result.demoOtp);setMessage('Mã OTP mới đã được gửi.');setCooldown(60)}catch(e){setError(getApiErrorMessage(e,'Không thể gửi lại OTP.'))}finally{setResending(false)}};
  return <AuthFrame><View style={s.card}><Text style={s.eyebrow}>XÁC THỰC EMAIL</Text><Text style={s.title}>Kích hoạt tài khoản</Text><Text style={s.subtitle}>Nhập mã OTP 6 số đã được gửi đến email đăng ký.</Text><AppInput label="Địa chỉ email" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><AppInput label="Mã OTP" value={otp} onChangeText={v=>setOtp(v.replace(/\D/g,'').slice(0,6))} keyboardType="number-pad" maxLength={6}/>{!!message&&<Text style={s.success}>{message}</Text>}{!!error&&<Text style={s.error}>{error}</Text>}<AppButton title="Xác minh tài khoản" loading={loading} onPress={()=>void verify()}/><Pressable disabled={cooldown>0||resending} onPress={()=>void resend()}><Text style={[s.link,{textAlign:'center',opacity:cooldown>0?.5:1}]}>{resending?'Đang gửi...':cooldown>0?`Gửi lại sau ${cooldown}s`:'Gửi lại mã OTP'}</Text></Pressable></View></AuthFrame>}
