import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { type Href,router,useFocusEffect } from 'expo-router';
import { useCallback,useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { photographerApi } from '@/apis/photographerApi';
import { productApi } from '@/apis/productApi';
import { RequireAuth } from '@/components/auth/RequireAuth';
import { EmptyState,ErrorState,LoadingState } from '@/components/ui/ScreenState';
import { ListPagination } from '@/components/ui/ListPagination';
import { Colors,FontFamily,Radius,Shadow } from '@/constants/theme';
import { useAuth } from '@/contexts/AuthContext';
import type { UserFavorite } from '@/types/auth';
import type { Photographer } from '@/types/photographer';
import type { Product } from '@/types/product';
import { getMediaUrl } from '@/utils/media';

type Saved={kind:'PRODUCT';data:Product}|{kind:'PROVIDER';data:Photographer};type Filter='ALL'|'PRODUCT'|'PROVIDER';
export default function Screen(){return <RequireAuth><Favorites/></RequireAuth>}
function Favorites(){const{user,toggleFavorite}=useAuth();const[items,setItems]=useState<Saved[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState<string|null>(null);const[q,setQ]=useState('');const[filter,setFilter]=useState<Filter>('ALL');const[page,setPage]=useState(1);const[nameSort,setNameSort]=useState(false);
  const load=useCallback(async(silent=false)=>{silent?setRefreshing(true):setLoading(true);try{setError(null);const favorites=(user?.favorites??[]) as UserFavorite[];const resolved=await Promise.all(favorites.map(async fav=>{try{return fav.targetType.toUpperCase()==='PRODUCT'?{kind:'PRODUCT' as const,data:await productApi.detail(String(fav.targetId))}:{kind:'PROVIDER' as const,data:await photographerApi.detail(String(fav.targetId))}}catch{return null}}));setItems(resolved.filter((v):v is Saved=>Boolean(v)))}catch{setError('Không thể tải danh sách yêu thích')}finally{setLoading(false);setRefreshing(false)}},[user?.favorites]);useFocusEffect(useCallback(()=>{void load();return undefined},[load]));
  const filtered=useMemo(()=>items.filter(item=>{if(filter!=='ALL'&&item.kind!==filter)return false;const name=item.kind==='PRODUCT'?item.data.name:item.data.businessName??'';return !q||name.toLowerCase().includes(q.toLowerCase())}).sort((a,b)=>nameSort?savedName(a).localeCompare(savedName(b),'vi'):0),[items,filter,q,nameSort]);const totalPages=Math.max(1,Math.ceil(filtered.length/8));const safePage=Math.min(page,totalPages);const visible=filtered.slice((safePage-1)*8,safePage*8);
  const remove=async(item:Saved)=>{await toggleFavorite(item.kind,item.data._id);setItems(v=>v.filter(saved=>!(saved.kind===item.kind&&saved.data._id===item.data._id)))};
  if(loading)return <LoadingState label="Đang mở bộ sưu tập..."/>;return <SafeAreaView style={s.safe} edges={['top']}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={Colors.primary}/>} contentContainerStyle={s.content}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.round}><Ionicons name="chevron-back" size={22}/></Pressable><View style={{flex:1}}><Text style={s.eyebrow}>LUMÉ ARCHIVE</Text><Text style={s.title}>Yêu thích <Text style={s.total}>{items.length}</Text></Text></View></View><View style={s.search}><Ionicons name="search" size={19} color={Colors.textMuted}/><TextInput value={q} onChangeText={value=>{setQ(value);setPage(1)}} placeholder="Tìm trong danh sách đã lưu..." placeholderTextColor={Colors.textMuted} style={s.input}/><Pressable onPress={()=>{setNameSort(value=>!value);setPage(1)}}><Ionicons name="text-outline" size={18} color={nameSort?Colors.primary:Colors.textMuted}/></Pressable></View><View style={s.filters}>{([['ALL',`Tất cả (${items.length})`],['PRODUCT',`Áo dài (${items.filter(v=>v.kind==='PRODUCT').length})`],['PROVIDER',`Chụp ảnh (${items.filter(v=>v.kind==='PROVIDER').length})`]] as [Filter,string][]).map(([key,label])=><Pressable key={key} onPress={()=>{setFilter(key);setPage(1)}} style={[s.chip,filter===key&&s.chipOn]}><Text style={[s.chipText,filter===key&&s.chipTextOn]}>{label}</Text></Pressable>)}</View>{error?<ErrorState message={error} onRetry={()=>void load()}/>:visible.length===0?<EmptyState title="Chưa có mục đã lưu" message="Nhấn biểu tượng trái tim tại áo dài hoặc gói chụp bạn yêu thích."/>:<View style={s.grid}>{visible.map(item=><SavedCard key={`${item.kind}-${item.data._id}`} item={item} onRemove={()=>void remove(item)}/>)}</View>}<ListPagination page={safePage} totalPages={totalPages} onChange={setPage}/><Text style={s.footer}>Hiển thị {visible.length} trong tổng số {filtered.length} mục phù hợp</Text></ScrollView></SafeAreaView>}
function SavedCard({item,onRemove}:{item:Saved;onRemove:()=>void}){const isProduct=item.kind==='PRODUCT';const data=item.data;const name=isProduct?(data as Product).name:(data as Photographer).businessName??'Gói chụp LUMÉ';const image=isProduct?(data as Product).images?.[0]:(data as Photographer).coverImage??(data as Photographer).media?.coverUrl;const price=isProduct?((data as Product).discountedPrice??(data as Product).basePrice):((data as Photographer).defaultPackage?.price??(data as Photographer).packages?.[0]?.price??0);const href=isProduct?`/product/${data._id}`:`/photographer/${data._id}`;return <Pressable onPress={()=>router.push(href as Href)} style={s.card}><View><Image source={getMediaUrl(image)} style={s.image} contentFit="cover"/><Text style={s.badge}>{isProduct?'ÁO DÀI':'CHỤP ẢNH'}</Text><Pressable onPress={e=>{e.stopPropagation();onRemove()}} style={s.heart}><Ionicons name="heart" size={20} color={Colors.primary}/></Pressable></View><View style={s.cardBody}><Text style={s.place}>{isProduct?'LUMÉ ÁO DÀI':'STUDIO'}</Text><Text numberOfLines={2} style={s.name}>{name}</Text><Text style={s.meta}>{isProduct?`${(data as Product).sizes?.join('/')||'Đủ size'} · Cọc ${money((data as Product).depositAmount??0)}`:`${(data as Photographer).rating?.averageRating?.toFixed(1)??'0.0'} ★ · ${(data as Photographer).address?.city??'Miền Trung'}`}</Text><View style={s.priceRow}><Text style={s.price}>{money(price)}</Text><Text style={s.link}>Chi tiết</Text></View></View></Pressable>}
const money=(v:number)=>new Intl.NumberFormat('vi-VN').format(v)+'đ';
const savedName=(item:Saved)=>item.kind==='PRODUCT'?item.data.name:item.data.businessName??'';
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:35,gap:16},header:{flexDirection:'row',alignItems:'center',gap:13},round:{width:42,height:42,borderRadius:99,backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,alignItems:'center',justifyContent:'center'},eyebrow:{fontFamily:FontFamily.bodyBold,fontSize:9,color:Colors.primary},title:{fontFamily:FontFamily.display,fontSize:25,color:Colors.text},total:{fontFamily:FontFamily.bodyBold,fontSize:11,color:Colors.primary},search:{height:49,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,backgroundColor:Colors.surface,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:8,...Shadow},input:{flex:1,fontFamily:FontFamily.body,fontSize:12,color:Colors.text},filters:{flexDirection:'row',gap:8},chip:{paddingHorizontal:13,paddingVertical:9,borderRadius:Radius.pill,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface},chipOn:{backgroundColor:Colors.primary,borderColor:Colors.primary},chipText:{fontFamily:FontFamily.bodyMedium,fontSize:10,color:Colors.textSecondary},chipTextOn:{color:Colors.white},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},card:{width:'48.3%',borderRadius:Radius.lg,overflow:'hidden',backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,...Shadow},image:{width:'100%',height:175,backgroundColor:Colors.primarySoft},badge:{position:'absolute',left:9,top:9,paddingHorizontal:7,paddingVertical:4,borderRadius:4,overflow:'hidden',backgroundColor:Colors.surface,fontFamily:FontFamily.bodyBold,fontSize:8,color:Colors.text},heart:{position:'absolute',right:9,top:9,width:34,height:34,borderRadius:99,backgroundColor:Colors.surface,alignItems:'center',justifyContent:'center'},cardBody:{padding:11},place:{fontFamily:FontFamily.bodyMedium,fontSize:8,color:Colors.textMuted},name:{fontFamily:FontFamily.display,fontSize:15,lineHeight:20,color:Colors.text,marginTop:5,minHeight:40},meta:{fontFamily:FontFamily.body,fontSize:9,color:Colors.textMuted,marginTop:5},priceRow:{borderTopWidth:1,borderTopColor:Colors.border,marginTop:10,paddingTop:10,flexDirection:'row',justifyContent:'space-between',alignItems:'center'},price:{fontFamily:FontFamily.bodyBold,fontSize:13,color:Colors.primary},link:{fontFamily:FontFamily.bodySemiBold,fontSize:9,color:Colors.primary,textDecorationLine:'underline'},footer:{fontFamily:FontFamily.body,fontSize:10,color:Colors.textMuted,textAlign:'center'}});
