import { Ionicons } from '@expo/vector-icons';
import { type Href,router } from 'expo-router';
import { useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { RequireAuth } from '@/components/auth/RequireAuth';
import { EmptyState,ErrorState,LoadingState } from '@/components/ui/ScreenState';
import { ListPagination } from '@/components/ui/ListPagination';
import { Colors,FontFamily,Radius,Shadow } from '@/constants/theme';
import { useNotifications } from '@/contexts/NotificationContext';
import type { NotificationItem } from '@/types/notification';

type Filter='ALL'|'UNREAD'|'ACTION'|'BOOKING';
const config:Record<string,{icon:keyof typeof Ionicons.glyphMap;color:string,bg:string}>={PAYMENT:{icon:'card-outline',color:Colors.primary,bg:Colors.primarySoft},BOOKING:{icon:'calendar-outline',color:Colors.primary,bg:Colors.primarySoft},HANDOVER:{icon:'bag-handle-outline',color:Colors.warning,bg:Colors.warningSoft},REFUND:{icon:'return-down-back-outline',color:Colors.success,bg:Colors.successSoft},DISPUTE:{icon:'alert-circle-outline',color:Colors.error,bg:Colors.errorSoft},SYSTEM:{icon:'information-outline',color:Colors.textSecondary,bg:'#F4F2F0'}};
const actionTypes=new Set(['PAYMENT','HANDOVER','DISPUTE']);
export default function Screen(){return <RequireAuth><Notifications/></RequireAuth>}
function Notifications(){const{notifications,unreadCount,loading,error,reload,markRead,markAllRead}=useNotifications();const[q,setQ]=useState('');const[filter,setFilter]=useState<Filter>('ALL');const[page,setPage]=useState(1);const items=useMemo(()=>notifications.filter(n=>{const text=`${n.title} ${n.content}`.toLowerCase();if(q&& !text.includes(q.toLowerCase()))return false;if(filter==='UNREAD')return !n.isRead;if(filter==='ACTION')return actionTypes.has(n.type);if(filter==='BOOKING')return n.type==='BOOKING';return true}),[notifications,q,filter]);const totalPages=Math.max(1,Math.ceil(items.length/10));const safePage=Math.min(page,totalPages);const visible=items.slice((safePage-1)*10,safePage*10);
  const open=async(item:NotificationItem)=>{if(!item.isRead)await markRead(item._id);const meta=item.metadata??{};const nested=typeof meta.booking==='object'&&meta.booking!==null?meta.booking as Record<string,unknown>:{};const bookingId=String(meta.bookingId??nested._id??'');const paymentCode=String(meta.paymentCode??meta.code??'');if(paymentCode)router.push({pathname:'/payment/result',params:{code:paymentCode}} as unknown as Href);else if(bookingId)router.push(`/booking/${bookingId}` as Href)};
  if(loading&&!notifications.length)return <LoadingState label="Đang tải thông báo..."/>;return <SafeAreaView style={s.safe} edges={['top']}><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={reload} tintColor={Colors.primary}/>} contentContainerStyle={s.content}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.round}><Ionicons name="chevron-back" size={22}/></Pressable><View style={{flex:1}}><Text style={s.title}>Thông báo {unreadCount>0&&<Text style={s.count}>{unreadCount} mới</Text>}</Text><Text style={s.sub}>Theo dõi booking và giao dịch của bạn</Text></View>{unreadCount>0&&<Pressable onPress={()=>void markAllRead()}><Ionicons name="checkmark-done" size={23} color={Colors.primary}/></Pressable>}</View><View style={s.search}><Ionicons name="search" size={19} color={Colors.textMuted}/><TextInput value={q} onChangeText={value=>{setQ(value);setPage(1)}} placeholder="Tìm theo mã booking, dịch vụ, nội dung..." placeholderTextColor={Colors.textMuted} style={s.input}/></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.filters}>{([['ALL',`Tất cả (${notifications.length})`],['UNREAD',`Chưa đọc (${unreadCount})`],['ACTION','Cần xử lý'],['BOOKING','Booking']] as [Filter,string][]).map(([key,label])=><Pressable key={key} onPress={()=>{setFilter(key);setPage(1)}} style={[s.chip,filter===key&&s.chipOn]}><Text style={[s.chipText,filter===key&&s.chipTextOn]}>{label}</Text></Pressable>)}</ScrollView>{error?<ErrorState message={error} onRetry={reload}/>:visible.length===0?<EmptyState title="Không có thông báo" message="Các cập nhật phù hợp sẽ xuất hiện tại đây."/>:<View style={s.list}>{visible.map(item=><NotificationCard key={item._id} item={item} onPress={()=>void open(item)}/>)}</View>}<ListPagination page={safePage} totalPages={totalPages} onChange={setPage}/></ScrollView></SafeAreaView>}
function NotificationCard({item,onPress}:{item:NotificationItem;onPress:()=>void}){const c=config[item.type]??config.SYSTEM;return <Pressable onPress={onPress} style={[s.card,!item.isRead&&s.unread]}><View style={[s.icon,{backgroundColor:c.bg}]}><Ionicons name={c.icon} size={22} color={c.color}/></View><View style={{flex:1}}><View style={s.cardTop}><Text style={[s.type,{color:c.color}]}>{item.type}</Text><Text style={s.time}>{formatTime(item.createdAt)}</Text></View><Text style={s.cardTitle}>{item.title}</Text><Text style={s.body}>{item.content}</Text>{!item.isRead&&<Text style={s.action}>Xem chi tiết →</Text>}</View></Pressable>}
const formatTime=(v:string)=>{const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit'})+' · '+d.toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})};
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:38,gap:16},header:{flexDirection:'row',alignItems:'center',gap:12},round:{width:40,height:40,borderRadius:99,borderWidth:1,borderColor:Colors.border,alignItems:'center',justifyContent:'center'},title:{fontFamily:FontFamily.display,fontSize:25,color:Colors.text},count:{fontFamily:FontFamily.bodyBold,fontSize:11,color:Colors.white,backgroundColor:Colors.primary},sub:{fontFamily:FontFamily.body,fontSize:10,color:Colors.textMuted,marginTop:3},search:{height:50,borderRadius:Radius.md,backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,paddingHorizontal:14,flexDirection:'row',alignItems:'center',gap:9,...Shadow},input:{flex:1,fontFamily:FontFamily.body,fontSize:12,color:Colors.text},filters:{gap:8},chip:{paddingHorizontal:15,paddingVertical:10,borderRadius:Radius.pill,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface},chipOn:{backgroundColor:Colors.primary,borderColor:Colors.primary},chipText:{fontFamily:FontFamily.bodyMedium,fontSize:11,color:Colors.textSecondary},chipTextOn:{color:Colors.white},list:{gap:12},card:{padding:15,borderRadius:Radius.lg,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface,flexDirection:'row',gap:12,...Shadow},unread:{borderLeftWidth:4,borderLeftColor:Colors.primary},icon:{width:46,height:46,borderRadius:99,alignItems:'center',justifyContent:'center'},cardTop:{flexDirection:'row',justifyContent:'space-between',gap:8},type:{fontFamily:FontFamily.bodyBold,fontSize:9},time:{fontFamily:FontFamily.body,fontSize:9,color:Colors.textMuted},cardTitle:{fontFamily:FontFamily.bodyBold,fontSize:14,lineHeight:19,color:Colors.text,marginTop:5},body:{fontFamily:FontFamily.body,fontSize:11,lineHeight:17,color:Colors.textSecondary,marginTop:5},action:{fontFamily:FontFamily.bodySemiBold,fontSize:10,color:Colors.primary,marginTop:10}});
