import { Ionicons } from '@expo/vector-icons';
import { type Href, router } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { paymentApi, type PaymentHistoryItem } from '@/apis/paymentApi';
import { RequireAuth } from '@/components/auth/RequireAuth';
import { ListPagination } from '@/components/ui/ListPagination';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/ScreenState';
import { StatusBadge } from '@/components/ui/StatusBadge';
import { Colors, FontFamily, Radius, Shadow } from '@/constants/theme';
import { getApiErrorMessage } from '@/utils/apiError';

const PAGE_SIZE=8;
type Filter='ALL'|'PAYMENT'|'REFUND';
export default function Screen(){return <RequireAuth><Payments/></RequireAuth>}
function Payments(){const[items,setItems]=useState<PaymentHistoryItem[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState<string|null>(null);const[q,setQ]=useState('');const[filter,setFilter]=useState<Filter>('ALL');const[page,setPage]=useState(1);const[oldest,setOldest]=useState(false);
  const load=async(silent=false)=>{silent?setRefreshing(true):setLoading(true);try{setError(null);const data=await paymentApi.history();setItems(Array.isArray(data)?data:[])}catch(e){setError(getApiErrorMessage(e,'Không thể tải lịch sử thanh toán'))}finally{setLoading(false);setRefreshing(false)}};useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>items.filter(item=>{if(filter==='REFUND'&&item.purpose!=='DEPOSIT_REFUND')return false;if(filter==='PAYMENT'&&item.purpose==='DEPOSIT_REFUND')return false;return !q||`${item.paymentCode} ${purpose(item.purpose)}`.toLowerCase().includes(q.toLowerCase())}).sort((a,b)=>(oldest?1:-1)*(new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime())),[items,q,filter,oldest]);const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE));const safePage=Math.min(page,totalPages);const visible=filtered.slice((safePage-1)*PAGE_SIZE,safePage*PAGE_SIZE);const update=(fn:()=>void)=>{setPage(1);fn()};
  if(loading)return <LoadingState label="Đang tải lịch sử thanh toán..."/>;return <SafeAreaView style={s.safe} edges={['top']}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={Colors.primary}/>} contentContainerStyle={s.content}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.round}><Ionicons name="chevron-back" size={22}/></Pressable><View style={{flex:1}}><Text style={s.title}>Lịch sử thanh toán</Text><Text style={s.sub}>Giao dịch PayOS và hoàn tiền của bạn</Text></View></View><View style={s.search}><Ionicons name="search" size={18} color={Colors.textMuted}/><TextInput value={q} onChangeText={value=>update(()=>setQ(value))} placeholder="Tìm mã giao dịch..." placeholderTextColor={Colors.textMuted} style={s.input}/></View><View style={s.tools}>{([['ALL','Tất cả'],['PAYMENT','Thanh toán'],['REFUND','Hoàn tiền']] as [Filter,string][]).map(([key,label])=><Pressable key={key} onPress={()=>update(()=>setFilter(key))} style={[s.chip,filter===key&&s.chipOn]}><Text style={[s.chipText,filter===key&&s.chipTextOn]}>{label}</Text></Pressable>)}<Pressable onPress={()=>update(()=>setOldest(v=>!v))} style={s.sort}><Ionicons name="swap-vertical" size={14} color={Colors.primary}/><Text style={s.sortText}>{oldest?'Cũ nhất':'Mới nhất'}</Text></Pressable></View>{error?<ErrorState message={error} onRetry={()=>void load()}/>:visible.length===0?<EmptyState title="Chưa có giao dịch" message="Các khoản thanh toán và hoàn tiền sẽ xuất hiện tại đây."/>:<View style={s.list}>{visible.map(item=><PaymentCard key={item._id} item={item}/>)}</View>}<ListPagination page={safePage} totalPages={totalPages} onChange={setPage}/><Text style={s.footer}>Hiển thị {visible.length} trong {filtered.length} giao dịch</Text></ScrollView></SafeAreaView>}
function PaymentCard({item}:{item:PaymentHistoryItem}){const refund=item.purpose==='DEPOSIT_REFUND';const ok=item.status==='SUCCESS';const bookingId=typeof item.bookingId==='string'?item.bookingId:item.bookingId?._id;return <Pressable disabled={!bookingId} onPress={()=>bookingId&&router.push(`/booking/${bookingId}` as Href)} style={s.card}><View style={[s.icon,{backgroundColor:refund?Colors.successSoft:Colors.primarySoft}]}><Ionicons name={refund?'return-down-back':'card-outline'} size={21} color={refund?Colors.success:Colors.primary}/></View><View style={{flex:1}}><View style={s.cardTop}><Text style={s.code}>{item.paymentCode}</Text><StatusBadge label={ok?'Thành công':item.status==='PENDING'?'Chờ xử lý':item.status==='CANCELLED'?'Đã hủy':'Thất bại'} tone={ok?'success':item.status==='PENDING'?'warning':'error'}/></View><Text style={s.purpose}>{purpose(item.purpose)}</Text><Text style={s.meta}>{formatDate(item.createdAt)} · {item.paymentMethod||'PAYOS'}</Text><Text style={[s.amount,refund&&{color:Colors.success}]}>{refund?'+':''}{money(item.amount)}</Text></View></Pressable>}
const purpose=(value:string)=>value==='DEPOSIT_PAYMENT'?'Đặt cọc giữ chỗ':value==='DEPOSIT_REFUND'?'Hoàn trả tiền cọc':value==='FULL_PAYMENT'?'Thanh toán trọn gói':value==='REMAINING_PAYMENT'?'Thanh toán còn lại':'Thanh toán dịch vụ';const money=(v=0)=>new Intl.NumberFormat('vi-VN').format(v)+'đ';const formatDate=(v:string)=>new Date(v).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:38,gap:14},header:{flexDirection:'row',alignItems:'center',gap:12},round:{width:40,height:40,borderRadius:99,borderWidth:1,borderColor:Colors.border,alignItems:'center',justifyContent:'center'},title:{fontFamily:FontFamily.display,fontSize:24,color:Colors.text},sub:{fontFamily:FontFamily.body,fontSize:10,color:Colors.textMuted,marginTop:3},search:{height:48,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,backgroundColor:Colors.surface,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:8,...Shadow},input:{flex:1,fontFamily:FontFamily.body,fontSize:11,color:Colors.text},tools:{flexDirection:'row',flexWrap:'wrap',gap:7},chip:{paddingHorizontal:12,paddingVertical:8,borderRadius:Radius.pill,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface},chipOn:{backgroundColor:Colors.primary,borderColor:Colors.primary},chipText:{fontFamily:FontFamily.bodyMedium,fontSize:9,color:Colors.textSecondary},chipTextOn:{color:Colors.white},sort:{marginLeft:'auto',paddingHorizontal:11,paddingVertical:8,borderRadius:Radius.pill,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface,flexDirection:'row',gap:4,alignItems:'center'},sortText:{fontFamily:FontFamily.bodySemiBold,fontSize:9,color:Colors.primary},list:{gap:10},card:{padding:14,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.lg,backgroundColor:Colors.surface,flexDirection:'row',gap:11,...Shadow},icon:{width:45,height:45,borderRadius:Radius.md,alignItems:'center',justifyContent:'center'},cardTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:7},code:{fontFamily:FontFamily.bodyBold,fontSize:11,color:Colors.text},purpose:{fontFamily:FontFamily.bodySemiBold,fontSize:11,color:Colors.text,marginTop:5},meta:{fontFamily:FontFamily.body,fontSize:8,color:Colors.textMuted,marginTop:4},amount:{fontFamily:FontFamily.bodyBold,fontSize:14,color:Colors.primary,marginTop:7},footer:{fontFamily:FontFamily.body,fontSize:9,color:Colors.textMuted,textAlign:'center'}});
