import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { userApi } from '@/apis/userApi';
import { RequireAuth } from '@/components/auth/RequireAuth';
import { AppButton } from '@/components/ui/AppButton';
import { AppInput } from '@/components/ui/AppInput';
import { LoadingState } from '@/components/ui/ScreenState';
import { Colors, FontFamily, Radius, Spacing } from '@/constants/theme';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/contexts/ToastContext';
import { getApiErrorMessage } from '@/utils/apiError';

const stylesList=[['TRADITIONAL','Truyền thống'],['MODERN','Cách tân'],['EDGY','Phá cách']] as const;
const colors=[['PASTEL','Pastel nhẹ'],['RED_GOLD','Đỏ · Vàng'],['DARK','Tông trầm'],['COLORFUL','Rực rỡ']] as const;
const occasions=[['GRADUATION','Kỷ yếu'],['WEDDING','Đám cưới'],['FESTIVAL','Lễ hội'],['EVENT','Sự kiện']] as const;
const sizes=['S','M','L','XL','XXL'];

export default function Route(){return <RequireAuth><Preferences/></RequireAuth>}
function Preferences(){const{refreshUser}=useAuth();const{show}=useToast();const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[style,setStyle]=useState<string|null>(null);const[color,setColor]=useState<string|null>(null);const[occasion,setOccasion]=useState<string|null>(null);const[size,setSize]=useState<string|null>(null);const[height,setHeight]=useState('');const[weight,setWeight]=useState('');
  useEffect(()=>{userApi.me().then(user=>{const value=user.preferences??{};setStyle(value.preferredAoDaiStyles?.[0]??null);setColor(value.favoriteColors?.[0]??null);setOccasion(value.preferredOccasions?.[0]??null);setSize(value.sizeInfo?.preferredSize??null);setHeight(value.sizeInfo?.height!=null?String(value.sizeInfo.height):'');setWeight(value.sizeInfo?.weight!=null?String(value.sizeInfo.weight):'')}).catch(cause=>show(getApiErrorMessage(cause,'Không thể tải sở thích'),'error')).finally(()=>setLoading(false))},[show]);
  const save=async()=>{setSaving(true);try{await userApi.updatePreferences({preferredAoDaiStyles:style?[style]:[],favoriteColors:color?[color]:[],preferredOccasions:occasion?[occasion]:[],sizeInfo:{preferredSize:size,height:height?Number(height):null,weight:weight?Number(weight):null}});await refreshUser();show('Đã lưu sở thích cá nhân','success')}catch(cause){show(getApiErrorMessage(cause,'Không thể lưu sở thích'),'error')}finally{setSaving(false)}};
  if(loading)return <LoadingState label="Đang tải sở thích..."/>;return <SafeAreaView style={s.safe} edges={['top']}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.back}><Ionicons name="chevron-back" size={22} color={Colors.text}/></Pressable><View><Text style={s.title}>Sở thích cá nhân</Text><Text style={s.sub}>Gợi ý dịch vụ phù hợp với bạn</Text></View><View style={s.spacer}/></View><ScrollView contentContainerStyle={s.content}><Group title="Phong cách áo dài"><Chips values={stylesList} selected={style} onChange={setStyle}/></Group><Group title="Tông màu ưa chuộng"><Chips values={colors} selected={color} onChange={setColor}/></Group><Group title="Dịp sử dụng"><Chips values={occasions} selected={occasion} onChange={setOccasion}/></Group><Group title="Kích cỡ thường dùng"><View style={s.chips}>{sizes.map(value=><Chip key={value} value={value} label={value} active={size===value} onPress={()=>setSize(size===value?null:value)}/>)}</View></Group><View style={s.measure}><AppInput label="CHIỀU CAO (CM)" value={height} onChangeText={setHeight} keyboardType="number-pad" placeholder="160" style={{flex:1}}/><AppInput label="CÂN NẶNG (KG)" value={weight} onChangeText={setWeight} keyboardType="number-pad" placeholder="52" style={{flex:1}}/></View><AppButton title="Lưu sở thích" loading={saving} onPress={()=>void save()}/></ScrollView></SafeAreaView>}
function Group({title,children}:{title:string;children:React.ReactNode}){return <View style={s.group}><Text style={s.groupTitle}>{title}</Text>{children}</View>}
function Chips({values,selected,onChange}:{values:readonly(readonly[string,string])[];selected:string|null;onChange:(value:string|null)=>void}){return <View style={s.chips}>{values.map(([value,label])=><Chip key={value} value={value} label={label} active={selected===value} onPress={()=>onChange(selected===value?null:value)}/>)}</View>}
function Chip({value,label,active,onPress}:{value:string;label:string;active:boolean;onPress:()=>void}){return <Pressable accessibilityRole="button" accessibilityState={{selected:active}} accessibilityLabel={label} onPress={onPress} style={[s.chip,active&&s.chipOn]}><Text style={[s.chipText,active&&s.chipTextOn]}>{label}</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},header:{height:66,paddingHorizontal:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',backgroundColor:Colors.surface,borderBottomWidth:1,borderBottomColor:Colors.border},back:{width:38,height:38,borderWidth:1,borderColor:Colors.border,borderRadius:99,alignItems:'center',justifyContent:'center'},spacer:{width:38},title:{fontFamily:FontFamily.display,fontSize:20,color:Colors.text,textAlign:'center'},sub:{fontFamily:FontFamily.body,fontSize:8,color:Colors.textMuted,textAlign:'center',marginTop:2},content:{padding:16,paddingBottom:40,gap:Spacing.md},group:{padding:15,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.lg,backgroundColor:Colors.surface,gap:11},groupTitle:{fontFamily:FontFamily.display,fontSize:17,color:Colors.text},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{paddingVertical:10,paddingHorizontal:14,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.pill,backgroundColor:Colors.surface},chipOn:{backgroundColor:Colors.primary,borderColor:Colors.primary},chipText:{fontFamily:FontFamily.bodySemiBold,fontSize:10,color:Colors.textSecondary},chipTextOn:{color:Colors.white},measure:{flexDirection:'row',gap:10}});
