import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { type Href,router } from 'expo-router';
import { useMemo,useState } from 'react';
import { Pressable,RefreshControl,ScrollView,StyleSheet,Text,TextInput,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { reviewApi } from '@/apis/reviewApi';
import { RequireAuth } from '@/components/auth/RequireAuth';
import { AppButton } from '@/components/ui/AppButton';
import { AppInput } from '@/components/ui/AppInput';
import { AppModal } from '@/components/ui/AppModal';
import { EmptyState,ErrorState,LoadingState } from '@/components/ui/ScreenState';
import { ListPagination } from '@/components/ui/ListPagination';
import { Colors,FontFamily,Radius,Shadow } from '@/constants/theme';
import { useToast } from '@/contexts/ToastContext';
import { useBookings } from '@/hooks/useBookings';
import type { Booking,BookingItem } from '@/types/booking';
import { bookingDate,formatDate,itemImage } from '@/utils/booking';
import { getApiErrorMessage } from '@/utils/apiError';
import { getMediaUrl } from '@/utils/media';

type Reviewable={booking:Booking,item:BookingItem};type Tab='PENDING'|'DONE';type Filter='ALL'|'PHOTO'|'PRODUCT';
export default function Screen(){return <RequireAuth><Reviews/></RequireAuth>}
function Reviews(){const{items:bookings,loading,refreshing,error,reload}=useBookings();const{show}=useToast();const[tab,setTab]=useState<Tab>('PENDING');const[filter,setFilter]=useState<Filter>('ALL');const[q,setQ]=useState('');const[page,setPage]=useState(1);const[selected,setSelected]=useState<Reviewable|null>(null);const[rating,setRating]=useState(5);const[comment,setComment]=useState('');const[saving,setSaving]=useState(false);
  const all=useMemo(()=>bookings.filter(b=>b.status==='COMPLETED').flatMap(booking=>booking.items.map(item=>({booking,item}))),[bookings]);const pending=all.filter(v=>!v.item.isReviewed);const done=all.filter(v=>v.item.isReviewed);const source=tab==='PENDING'?pending:done;const filtered=source.filter(v=>{if(filter==='PHOTO'&&v.item.itemType!=='PHOTOGRAPHY_PACKAGE')return false;if(filter==='PRODUCT'&&v.item.itemType!=='PRODUCT')return false;return !q||reviewTitle(v.item).toLowerCase().includes(q.toLowerCase())});const totalPages=Math.max(1,Math.ceil(filtered.length/8));const safePage=Math.min(page,totalPages);const visible=filtered.slice((safePage-1)*8,safePage*8);
  const submit=async()=>{if(!selected||!comment.trim()){show('Vui lòng nhập nội dung nhận xét','error');return}setSaving(true);try{const product=entityId(selected.item.productId);const pack=entityId(selected.item.photographyPackageId);await reviewApi.create({bookingId:selected.booking._id,bookingItemId:selected.item._id,rating,comment:comment.trim(),productId:product,photographyPackageId:pack});setSelected(null);setComment('');setRating(5);await reload();show('Cảm ơn bạn đã gửi đánh giá','success')}catch(e){show(getApiErrorMessage(e,'Gửi đánh giá thất bại'),'error')}finally{setSaving(false)}};
  if(loading)return <LoadingState label="Đang tải đánh giá..."/>;return <SafeAreaView style={s.safe} edges={['top']}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={reload} tintColor={Colors.primary}/>} contentContainerStyle={s.content}><View style={s.header}><Pressable style={s.round} onPress={()=>router.back()}><Ionicons name="chevron-back" size={22}/></Pressable><View style={{flex:1}}><Text style={s.title}>Đánh giá của tôi</Text><Text style={s.subtitle}>Quản lý các dịch vụ cần đánh giá và đã gửi</Text></View></View><View style={s.tabs}><Pressable onPress={()=>{setTab('PENDING');setPage(1)}} style={[s.tab,tab==='PENDING'&&s.tabOn]}><Text style={[s.tabText,tab==='PENDING'&&s.tabTextOn]}>Cần bạn đánh giá ({pending.length})</Text></Pressable><Pressable onPress={()=>{setTab('DONE');setPage(1)}} style={[s.tab,tab==='DONE'&&s.tabOn]}><Text style={[s.tabText,tab==='DONE'&&s.tabTextOn]}>Đã đánh giá ({done.length})</Text></Pressable></View><View style={s.search}><Ionicons name="search" size={19} color={Colors.textMuted}/><TextInput value={q} onChangeText={value=>{setQ(value);setPage(1)}} placeholder="Tìm đánh giá dịch vụ..." placeholderTextColor={Colors.textMuted} style={s.input}/></View><View style={s.filters}>{([['ALL','Tất cả'],['PHOTO','Chụp ảnh'],['PRODUCT','Thuê áo dài']] as [Filter,string][]).map(([key,label])=><Pressable key={key} onPress={()=>{setFilter(key);setPage(1)}} style={[s.chip,filter===key&&s.chipOn]}><Text style={[s.chipText,filter===key&&s.chipTextOn]}>{label}</Text></Pressable>)}</View>{error?<ErrorState message={error} onRetry={reload}/>:visible.length===0?<EmptyState title={tab==='PENDING'?'Không có dịch vụ chờ đánh giá':'Chưa có đánh giá đã gửi'} message={tab==='PENDING'?'Các dịch vụ hoàn tất chưa đánh giá sẽ xuất hiện tại đây.':'Sau khi gửi, đánh giá của bạn sẽ được ghi nhận tại đây.'}/>:<View style={s.list}>{visible.map(value=><ReviewCard key={value.item._id} value={value} done={tab==='DONE'} onReview={()=>setSelected(value)}/>)}</View>}<ListPagination page={safePage} totalPages={totalPages} onChange={setPage}/></ScrollView><AppModal visible={Boolean(selected)} title="Đánh giá chất lượng dịch vụ" onClose={()=>setSelected(null)}><View style={s.modal}><Text style={s.reviewing}>{selected&&reviewTitle(selected.item)}</Text><Text style={s.label}>CHỌN MỨC ĐỘ HÀI LÒNG</Text><View style={s.stars}>{[1,2,3,4,5].map(star=><Pressable key={star} onPress={()=>setRating(star)}><Ionicons name={star<=rating?'star':'star-outline'} size={32} color="#E99B19"/></Pressable>)}</View><AppInput label="Nội dung nhận xét" multiline numberOfLines={4} value={comment} onChangeText={setComment} placeholder="Chia sẻ trải nghiệm của bạn..." style={s.comment}/><AppButton title="Gửi đánh giá" loading={saving} onPress={()=>void submit()}/></View></AppModal></SafeAreaView>}
function ReviewCard({value,done,onReview}:{value:Reviewable;done:boolean;onReview:()=>void}){const{booking,item}=value;return <View style={s.card}><View style={s.cardBody}><Image source={getMediaUrl(itemImage(item))} style={s.image} contentFit="cover"/><View style={{flex:1}}><Text style={s.type}>{item.itemType==='PRODUCT'?'THUÊ ÁO DÀI':'CHỤP ẢNH'}</Text><Text style={s.name}>{reviewTitle(item)}</Text><Text style={s.meta}>Hoàn tất {formatDate(bookingDate(booking))} · #{booking.bookingCode}</Text></View></View><View style={s.cardBottom}>{done?<><View style={s.done}><Ionicons name="checkmark-circle" size={16} color={Colors.success}/><Text style={s.doneText}>Đã gửi đánh giá</Text></View><Pressable onPress={()=>router.push(`/booking/${booking._id}` as Href)}><Text style={s.link}>Xem đơn</Text></Pressable></>:<><Text style={s.deadline}>SẴN SÀNG ĐÁNH GIÁ</Text><Pressable onPress={onReview} style={s.button}><Text style={s.buttonText}>Viết đánh giá</Text></Pressable></>}</View></View>}
const entityId=(value:BookingItem['productId']|BookingItem['photographyPackageId'])=>typeof value==='string'?value:value?value._id:undefined;
const reviewTitle=(item:BookingItem)=>item.itemType==='PRODUCT'?(typeof item.productId==='object'&&item.productId?item.productId.name:'Áo dài LUMÉ')??'Áo dài LUMÉ':(typeof item.photographyPackageId==='object'&&item.photographyPackageId?item.photographyPackageId.name:item.packageSnapshot?.name)??'Gói chụp ảnh';
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:35,gap:15},header:{flexDirection:'row',alignItems:'center',gap:12},round:{width:40,height:40,borderRadius:99,alignItems:'center',justifyContent:'center'},title:{fontFamily:FontFamily.display,fontSize:24,color:Colors.primary},subtitle:{fontFamily:FontFamily.body,fontSize:10,color:Colors.textMuted,marginTop:3},tabs:{padding:5,borderRadius:Radius.md,backgroundColor:'#F2ECE6',flexDirection:'row'},tab:{flex:1,minHeight:42,borderRadius:Radius.sm,alignItems:'center',justifyContent:'center'},tabOn:{backgroundColor:Colors.primary},tabText:{fontFamily:FontFamily.bodySemiBold,fontSize:10,color:Colors.textSecondary},tabTextOn:{color:Colors.white},search:{height:49,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,backgroundColor:Colors.surface,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:8},input:{flex:1,fontFamily:FontFamily.body,fontSize:12,color:Colors.text},filters:{flexDirection:'row',gap:8},chip:{paddingHorizontal:14,paddingVertical:9,borderRadius:Radius.pill,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface},chipOn:{backgroundColor:Colors.primary,borderColor:Colors.primary},chipText:{fontFamily:FontFamily.bodyMedium,fontSize:10,color:Colors.textSecondary},chipTextOn:{color:Colors.white},list:{gap:12},card:{padding:15,borderRadius:Radius.lg,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface,...Shadow},cardBody:{flexDirection:'row',gap:13},image:{width:78,height:78,borderRadius:Radius.md,backgroundColor:Colors.primarySoft},type:{fontFamily:FontFamily.bodyBold,fontSize:9,color:Colors.textMuted},name:{fontFamily:FontFamily.bodyBold,fontSize:14,lineHeight:19,color:Colors.text,marginTop:5},meta:{fontFamily:FontFamily.body,fontSize:9,lineHeight:15,color:Colors.textMuted,marginTop:5},cardBottom:{borderTopWidth:1,borderTopColor:Colors.border,marginTop:13,paddingTop:12,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},deadline:{fontFamily:FontFamily.bodyBold,fontSize:8,color:Colors.warning},button:{paddingHorizontal:17,paddingVertical:10,borderRadius:Radius.md,backgroundColor:Colors.primary},buttonText:{fontFamily:FontFamily.bodySemiBold,fontSize:10,color:Colors.white},done:{flexDirection:'row',alignItems:'center',gap:5},doneText:{fontFamily:FontFamily.bodySemiBold,fontSize:9,color:Colors.success},link:{fontFamily:FontFamily.bodySemiBold,fontSize:10,color:Colors.primary},modal:{gap:14,paddingBottom:15},reviewing:{fontFamily:FontFamily.display,fontSize:18,color:Colors.text,textAlign:'center'},label:{fontFamily:FontFamily.bodyBold,fontSize:9,color:Colors.textMuted,textAlign:'center'},stars:{flexDirection:'row',gap:7,justifyContent:'center'},comment:{height:105,textAlignVertical:'top',paddingTop:12}});
