import { Ionicons } from '@expo/vector-icons';
import { type Href,router } from 'expo-router';
import { useState } from 'react';
import { Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { authApi } from '@/apis/authApi';
import { RequireAuth } from '@/components/auth/RequireAuth';
import { AppButton } from '@/components/ui/AppButton';
import { AppInput } from '@/components/ui/AppInput';
import { Colors,FontFamily,Radius,Shadow } from '@/constants/theme';
import { useAuth } from '@/contexts/AuthContext';
import { getApiErrorMessage } from '@/utils/apiError';

export default function Screen(){return <RequireAuth><Security/></RequireAuth>}
function Security(){const{logout}=useAuth();const[current,setCurrent]=useState('');const[next,setNext]=useState('');const[confirm,setConfirm]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const submit=async()=>{if(!current){setError('Vui lòng nhập mật khẩu hiện tại.');return}if(next.length<8||!/[A-Za-z]/.test(next)||!/[0-9]/.test(next)){setError('Mật khẩu mới cần ít nhất 8 ký tự, gồm chữ và số.');return}if(next!==confirm){setError('Mật khẩu xác nhận không trùng khớp.');return}setLoading(true);setError('');try{await authApi.changePassword({currentPassword:current,newPassword:next});await logout();router.replace('/(auth)/login' as Href)}catch(e){setError(getApiErrorMessage(e,'Không thể đổi mật khẩu.'))}finally{setLoading(false)}};return <SafeAreaView style={s.safe} edges={['top']}><ScrollView contentContainerStyle={s.content}><View style={s.header}><Pressable style={s.back} onPress={()=>router.back()}><Ionicons name="chevron-back" size={22}/></Pressable><View><Text style={s.eyebrow}>BẢO MẬT TÀI KHOẢN</Text><Text style={s.title}>Đổi mật khẩu</Text></View></View><View style={s.notice}><Ionicons name="shield-checkmark" size={23} color={Colors.success}/><Text style={s.noticeText}>Sau khi đổi mật khẩu, các phiên đăng nhập cũ sẽ bị thu hồi và bạn cần đăng nhập lại.</Text></View><View style={s.card}><AppInput label="Mật khẩu hiện tại" value={current} onChangeText={setCurrent} secureTextEntry/><AppInput label="Mật khẩu mới" value={next} onChangeText={setNext} secureTextEntry hint="Tối thiểu 8 ký tự, gồm chữ và số."/><AppInput label="Xác nhận mật khẩu mới" value={confirm} onChangeText={setConfirm} secureTextEntry/>{!!error&&<Text style={s.error}>{error}</Text>}<AppButton title="Đổi mật khẩu" loading={loading} onPress={()=>void submit()}/></View></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{padding:18,paddingBottom:40,gap:16},header:{flexDirection:'row',alignItems:'center',gap:12},back:{width:42,height:42,borderRadius:99,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface,alignItems:'center',justifyContent:'center'},eyebrow:{fontFamily:FontFamily.bodyBold,fontSize:8,color:Colors.primary},title:{fontFamily:FontFamily.display,fontSize:25,color:Colors.text},notice:{padding:15,borderRadius:Radius.md,backgroundColor:Colors.successSoft,flexDirection:'row',alignItems:'center',gap:10},noticeText:{flex:1,fontFamily:FontFamily.body,fontSize:10,lineHeight:16,color:Colors.success},card:{padding:18,borderRadius:Radius.lg,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface,gap:15,...Shadow},error:{fontFamily:FontFamily.bodyMedium,fontSize:10,lineHeight:16,color:Colors.error,backgroundColor:Colors.errorSoft,padding:10,borderRadius:Radius.sm}});
