import type { Booking, BookingItem, BookingProvider } from '@/types/booking';

export const bookingStatus:Record<string,{label:string;tone:'neutral'|'success'|'warning'|'error'|'info'}>={DRAFT:{label:'Bản nháp',tone:'neutral'},PENDING_PAYMENT:{label:'Chờ thanh toán',tone:'warning'},DEPOSIT_PAID:{label:'Đã đặt cọc',tone:'success'},CONFIRMED:{label:'Đã xác nhận',tone:'success'},PICKUP_PENDING:{label:'Sẵn sàng nhận áo',tone:'info'},PICKED_UP:{label:'Đã nhận áo',tone:'success'},RETURN_PENDING:{label:'Sắp đến hạn trả',tone:'warning'},RETURNED:{label:'Đã trả áo',tone:'info'},IN_PROGRESS:{label:'Đang thực hiện',tone:'info'},AWAITING_REVIEW:{label:'Chờ bạn xác nhận',tone:'warning'},COMBO_PHOTOS_APPROVED:{label:'Ảnh đã duyệt',tone:'success'},COMPLETED:{label:'Hoàn tất',tone:'neutral'},CANCELLED:{label:'Đã hủy',tone:'error'},DISPUTED:{label:'Đang xử lý sự cố',tone:'error'},PARTIALLY_REFUNDED:{label:'Hoàn một phần',tone:'warning'},REFUNDED:{label:'Đã hoàn tiền',tone:'neutral'}};
export const terminalStatuses=new Set(['COMPLETED','CANCELLED','REFUNDED','PARTIALLY_REFUNDED']);
export const attentionStatuses=new Set(['PENDING_PAYMENT','PICKUP_PENDING','RETURN_PENDING','AWAITING_REVIEW','DISPUTED']);
export const itemName=(item:BookingItem)=>item.itemType==='PRODUCT'?(item.productId&&typeof item.productId==='object'?item.productId.name:'Áo dài'):(item.photographyPackageId&&typeof item.photographyPackageId==='object'?item.photographyPackageId.name:item.packageSnapshot?.name)||'Gói chụp ảnh';
export const itemImage=(item:BookingItem)=>item.itemType==='PRODUCT'?(item.productId&&typeof item.productId==='object'?item.productId.images?.[0]:undefined):(item.photographyPackageId&&typeof item.photographyPackageId==='object'?item.photographyPackageId.images?.[0]:undefined);
export const itemProvider=(item:BookingItem):BookingProvider|undefined=>{if(item.providerId&&typeof item.providerId==='object')return item.providerId;if(item.productId&&typeof item.productId==='object'&&item.productId.providerId&&typeof item.productId.providerId==='object')return item.productId.providerId;return undefined};
export const bookingDate=(booking:Booking)=>{const photo=booking.items.find(item=>item.itemType==='PHOTOGRAPHY_PACKAGE');const rental=booking.items.find(item=>item.itemType==='PRODUCT');return photo?.shootDate||rental?.rentalFrom||booking.createdAt||''};
export const bookingTitle=(booking:Booking)=>booking.bookingType==='COMBO'?'Combo áo dài & chụp ảnh':booking.items.length===1?itemName(booking.items[0]):`${itemName(booking.items[0])} +${booking.items.length-1}`;
export const formatDate=(value?:string|null)=>{if(!value)return 'Chưa cập nhật';const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric'}).format(date)};
export const formatDateTime=(value?:string|null)=>{if(!value)return 'Chưa cập nhật';const date=new Date(value);return Number.isNaN(date.getTime())?value:new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(date)};
