export enum ErrorCode {
  ValidationError = 'VALIDATION_ERROR',
  EmailAlreadyExists = 'EMAIL_ALREADY_EXISTS',
  PhoneAlreadyExists = 'PHONE_ALREADY_EXISTS',
  InvalidCredentials = 'INVALID_CREDENTIALS',
  EmailNotVerified = 'EMAIL_NOT_VERIFIED',
  AccountDisabled = 'ACCOUNT_DISABLED',
  InvalidOtp = 'INVALID_OTP',
  OtpExpired = 'OTP_EXPIRED',
  OtpMaxAttemptsExceeded = 'OTP_MAX_ATTEMPTS_EXCEEDED',
  InvalidRefreshToken = 'INVALID_REFRESH_TOKEN',
  SessionRevoked = 'SESSION_REVOKED',
  PermissionDenied = 'PERMISSION_DENIED',
  LastActiveAdminProtected = 'LAST_ACTIVE_ADMIN_PROTECTED',
  RateLimitExceeded = 'RATE_LIMIT_EXCEEDED',
  InvalidOAuthState = 'INVALID_OAUTH_STATE',
  InvalidOAuthCode = 'INVALID_OAUTH_CODE',
  NotFound = 'NOT_FOUND',
  InternalError = 'INTERNAL_ERROR',
}
