import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { BrandHeader } from '@/components/ui/BrandHeader';
import { SectionHeader } from '@/components/ui/SectionHeader';
import { ProductCard } from '@/components/product/ProductCard';
import { Colors, FontFamily, Radius, Shadow, Spacing } from '@/constants/theme';
import { useFeaturedProducts } from '@/hooks/useFeaturedProducts';
import { type Href, router } from 'expo-router';
import { useFeaturedPhotographers } from '@/hooks/useFeaturedPhotographers';

const services = [['sparkles-outline', 'Áo dài nữ', '20 mẫu'], ['people-outline', 'Áo dài đôi', '27 mẫu'], ['school-outline', 'Kỷ yếu', '34 mẫu'], ['image-outline', 'Ngoại cảnh', '12 gói']] as const;
export default function HomeScreen() {
  const { products } = useFeaturedProducts(4);
  const { items: photographers } = useFeaturedPhotographers(2);
  return <SafeAreaView style={s.safe} edges={['top']}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.content}>
    <BrandHeader />
    <LinearGradient colors={[Colors.primary, Colors.primaryDark]} style={s.hero}>
      <Text style={s.eyebrow}>THUÊ ÁO DÀI & CHỤP ẢNH TRỌN GÓI</Text><Text style={s.heroTitle}>Chọn áo dài.{`\n`}Đặt lịch chụp. Tỏa sáng.</Text><Text style={s.heroBody}>Hơn 120+ mẫu áo dài cao cấp cùng photographer chuyên nghiệp tại Huế, Đà Nẵng & Hội An.</Text>
      <View style={s.heroActions}><Pressable style={s.whiteButton} onPress={()=>router.push('/(tabs)/rentals' as Href)}><Text style={s.whiteButtonText}>Khám phá ngay ↗</Text></Pressable><Pressable style={s.ghostButton} onPress={()=>router.push('/(tabs)/photography' as Href)}><Text style={s.ghostText}>Xem gói chụp</Text></Pressable></View>
      <View style={s.stats}>{[['120+', 'Mẫu áo dài'], ['30+', 'Gói chụp ảnh'], ['4.9/5', 'Đánh giá']].map(([v, l]) => <View key={l} style={s.stat}><Text style={s.statValue}>{v}</Text><Text style={s.statLabel}>{l}</Text></View>)}</View>
    </LinearGradient>
    <View style={s.searchCard}><View style={s.searchHead}><Text style={s.cardTitle}>Tìm kiếm & Đặt lịch nhanh</Text><Text style={s.link}>Đặt cọc online</Text></View><View style={s.formGrid}>{[['DỊCH VỤ', 'Thuê áo dài'], ['NHU CẦU', 'Kỷ yếu / Ngoại cảnh'], ['NGÀY DỰ KIẾN', 'Chọn ngày'], ['ĐỊA ĐIỂM', 'TP. Huế']].map(([l, v]) => <View key={l} style={s.field}><Text style={s.fieldLabel}>{l}</Text><Text style={s.fieldValue}>{v}</Text></View>)}</View><Pressable style={s.primaryButton} onPress={()=>router.push('/(tabs)/rentals' as Href)}><Ionicons name="search" color={Colors.white} size={16}/><Text style={s.primaryButtonText}>Tìm dịch vụ phù hợp</Text></Pressable></View>
    <SectionHeader title="Dịch vụ nổi bật" onPress={()=>router.push('/(tabs)/rentals' as Href)} />
    <View style={s.services}>{services.map(([icon, title, count],index) => <Pressable onPress={()=>router.push(index<2?'/(tabs)/rentals' as Href:'/(tabs)/photography' as Href)} key={title} style={s.service}><View style={s.serviceIcon}><Ionicons name={icon} size={24} color={Colors.primary}/></View><Text style={s.serviceTitle}>{title}</Text><Text style={s.serviceCount}>{count}</Text></Pressable>)}</View>
    <SectionHeader title="Áo dài nổi bật" onPress={()=>router.push('/(tabs)/rentals' as Href)} />
    <View style={s.productRow}>{products.slice(0,2).map(product => <ProductCard key={product._id} product={product}/>)}</View>
    <SectionHeader title="Gói chụp ảnh nổi bật" onPress={()=>router.push('/(tabs)/photography' as Href)} />
    {photographers.map((photographer, i) => {const pack=photographer.defaultPackage??photographer.packages?.[0];return <Pressable key={photographer._id} style={s.package} onPress={()=>router.push(`/photographer/${photographer._id}?packageId=${pack?._id??''}` as Href)}><View style={s.packageImage}><Ionicons name={i ? 'image-outline' : 'camera-outline'} size={26} color={Colors.textMuted}/></View><View style={s.packageText}><Text style={s.productName}>{pack?.name??photographer.businessName??'Gói chụp ảnh'}</Text><Text style={s.muted}>{pack?.editedPhotosCount??0} ảnh sửa</Text><Text style={s.price}>{new Intl.NumberFormat('vi-VN').format(pack?.price??0)}đ</Text></View><Text style={s.link}>Chi tiết</Text></Pressable>})}
  </ScrollView></SafeAreaView>;
}

const s = StyleSheet.create({
  safe:{flex:1,backgroundColor:Colors.background},content:{paddingHorizontal:Spacing.lg,paddingBottom:28,gap:22},hero:{borderRadius:Radius.lg,padding:20,...Shadow},eyebrow:{color:'#E9C9CF',fontFamily:FontFamily.bodySemiBold,fontSize:10},heroTitle:{color:Colors.white,fontFamily:FontFamily.display,fontSize:29,lineHeight:36,marginTop:12},heroBody:{color:'#F5EDEF',fontFamily:FontFamily.body,fontSize:13,lineHeight:20,marginTop:10},heroActions:{flexDirection:'row',gap:10,marginTop:18},whiteButton:{backgroundColor:Colors.white,borderRadius:Radius.pill,paddingHorizontal:16,paddingVertical:11},whiteButtonText:{color:Colors.primary,fontFamily:FontFamily.bodySemiBold,fontSize:12},ghostButton:{borderWidth:1,borderColor:'#A96B76',borderRadius:Radius.pill,paddingHorizontal:16,paddingVertical:11},ghostText:{color:Colors.white,fontFamily:FontFamily.bodyMedium,fontSize:12},stats:{flexDirection:'row',borderTopWidth:1,borderTopColor:'#9B5662',marginTop:20,paddingTop:16},stat:{flex:1,alignItems:'center'},statValue:{color:Colors.white,fontFamily:FontFamily.display,fontSize:19},statLabel:{color:'#E9C9CF',fontFamily:FontFamily.body,fontSize:9},
  searchCard:{backgroundColor:Colors.surface,borderRadius:Radius.lg,padding:16,borderWidth:1,borderColor:Colors.border,...Shadow},searchHead:{flexDirection:'row',justifyContent:'space-between',marginBottom:14},cardTitle:{fontFamily:FontFamily.bodyBold,fontSize:15,color:Colors.text},link:{color:Colors.primary,fontFamily:FontFamily.bodyMedium,fontSize:11},formGrid:{flexDirection:'row',flexWrap:'wrap',gap:8},field:{width:'48.5%',padding:11,backgroundColor:Colors.background,borderRadius:Radius.md,borderWidth:1,borderColor:'#F0E9E4'},fieldLabel:{color:Colors.textMuted,fontFamily:FontFamily.bodySemiBold,fontSize:9},fieldValue:{color:Colors.text,fontFamily:FontFamily.body,fontSize:12,marginTop:5},primaryButton:{height:44,marginTop:12,borderRadius:Radius.md,backgroundColor:Colors.primary,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center'},primaryButtonText:{color:Colors.white,fontFamily:FontFamily.bodySemiBold,fontSize:13},
  services:{flexDirection:'row',justifyContent:'space-between'},service:{alignItems:'center',width:'23%'},serviceIcon:{width:52,height:52,alignItems:'center',justifyContent:'center',borderRadius:Radius.md,backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border},serviceTitle:{marginTop:7,fontFamily:FontFamily.bodyMedium,fontSize:11,color:Colors.text},serviceCount:{fontFamily:FontFamily.body,fontSize:9,color:Colors.textMuted},productRow:{flexDirection:'row',gap:12},productCard:{flex:1,backgroundColor:Colors.surface,borderRadius:Radius.md,overflow:'hidden',borderWidth:1,borderColor:Colors.border,...Shadow},productImage:{height:160,backgroundColor:'#F4EFEF',alignItems:'center',justifyContent:'center'},imageText:{color:'#C7BCBD',fontFamily:FontFamily.bodyMedium,fontSize:10},heart:{position:'absolute',top:10,right:10},productInfo:{padding:11},productBrand:{color:Colors.textMuted,fontFamily:FontFamily.bodyMedium,fontSize:8},productName:{color:Colors.text,fontFamily:FontFamily.bodySemiBold,fontSize:12,lineHeight:17,marginTop:3},rating:{color:'#EE9B15',fontFamily:FontFamily.bodyMedium,fontSize:10,marginVertical:6},price:{color:Colors.primary,fontFamily:FontFamily.bodyBold,fontSize:14,marginTop:5},perDay:{color:Colors.textMuted,fontFamily:FontFamily.body,fontSize:9},package:{flexDirection:'row',alignItems:'center',backgroundColor:Colors.surface,padding:12,borderRadius:Radius.md,borderWidth:1,borderColor:Colors.border,...Shadow},packageImage:{width:76,height:68,backgroundColor:'#F2EFED',borderRadius:Radius.sm,alignItems:'center',justifyContent:'center'},packageText:{flex:1,marginLeft:12},muted:{color:Colors.textMuted,fontFamily:FontFamily.body,fontSize:10},
});
