import { Ionicons } from '@expo/vector-icons';
import { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { ProductCard } from '@/components/product/ProductCard';
import { BrandHeader } from '@/components/ui/BrandHeader';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/ScreenState';
import { Colors, FontFamily, Radius, Shadow, Spacing } from '@/constants/theme';
import { useProducts } from '@/hooks/useProducts';
import type { ProductFilters } from '@/types/product';

const categories=[{label:'Tất cả',value:''},{label:'Áo dài nữ',value:'female'},{label:'Áo dài nam',value:'male'},{label:'Áo dài đôi',value:'couple'}];
const locations=['','Huế','Đà Nẵng','Hội An']; const sizes=['','S','M','L','XL'];
const sorts: Array<{label:string;value:ProductFilters['sort']}>= [{label:'Mới nhất',value:'newest'},{label:'Đánh giá cao',value:'rating_desc'},{label:'Giá thấp',value:'price_asc'},{label:'Giá cao',value:'price_desc'}];

export default function RentalsScreen(){const [draft,setDraft]=useState('');const [search,setSearch]=useState('');const [category,setCategory]=useState('');const [locationIndex,setLocationIndex]=useState(0);const [sizeIndex,setSizeIndex]=useState(0);const [sortIndex,setSortIndex]=useState(0);const [page,setPage]=useState(1);const filters:ProductFilters={search:search||undefined,types:category?[category]:undefined,providerLocation:locations[locationIndex]||undefined,sizes:sizes[sizeIndex]?[sizes[sizeIndex]]:undefined,sort:sorts[sortIndex].value,page,limit:10};const {products,loading,error,total,totalPages,reload}=useProducts(filters);const change=(fn:()=>void)=>{setPage(1);fn()};
return <SafeAreaView style={s.safe} edges={['top']}><ScrollView keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false} contentContainerStyle={s.content}><BrandHeader/><Text style={s.eyebrow}>MẪU ÁO DÀI ĐÃ XÁC MINH</Text><Text style={s.title}>Thuê áo dài tại miền Trung</Text><Text style={s.subtitle}>Chọn mẫu, size, hình thức thuê và thời gian nhận trả phù hợp.</Text><View style={s.stats}>{[['120+','Mẫu áo dài'],['15','Cửa hàng'],['4.9/5','Đánh giá']].map(([v,l])=><View key={l} style={s.stat}><Text style={s.statValue}>{v}</Text><Text style={s.statLabel}>{l}</Text></View>)}</View>
<View style={s.filterCard}><View style={s.searchInput}><Ionicons name="search" size={18} color={Colors.textMuted}/><TextInput value={draft} onChangeText={setDraft} onSubmitEditing={()=>change(()=>setSearch(draft.trim()))} placeholder="Tên hoặc mô tả áo dài..." placeholderTextColor={Colors.textMuted} style={s.input}/></View><View style={s.filterRow}><Filter label="KHU VỰC" value={locations[locationIndex]||'Tất cả khu vực'} onPress={()=>change(()=>setLocationIndex((locationIndex+1)%locations.length))}/><Filter label="KÍCH CỠ" value={sizes[sizeIndex]||'Tất cả size'} onPress={()=>change(()=>setSizeIndex((sizeIndex+1)%sizes.length))}/></View><Pressable style={s.searchButton} onPress={()=>change(()=>setSearch(draft.trim()))}><Ionicons name="search" color={Colors.white} size={17}/><Text style={s.searchText}>Tìm áo dài ngay</Text></Pressable></View>
<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.chips}>{categories.map(item=><Pressable key={item.value} onPress={()=>change(()=>setCategory(item.value))} style={[s.chip,category===item.value&&s.chipActive]}><Text style={[s.chipText,category===item.value&&s.chipTextActive]}>{item.label}</Text></Pressable>)}</ScrollView><View style={s.listHead}><Text style={s.result}>{total} mẫu phù hợp</Text><Pressable style={s.sort} onPress={()=>change(()=>setSortIndex((sortIndex+1)%sorts.length))}><Text style={s.sortText}>{sorts[sortIndex].label} ⌄</Text></Pressable></View>
{loading?<LoadingState label="Đang tìm áo dài..."/>:error?<ErrorState message={error} onRetry={reload}/>:products.length===0?<EmptyState title="Không tìm thấy áo dài" message="Hãy thử thay đổi từ khóa hoặc bộ lọc."/>:<View style={s.grid}>{products.map(product=><ProductCard key={product._id} product={product}/>)}</View>}
{!loading&&totalPages>1&&<View style={s.pagination}><Pressable disabled={page===1} onPress={()=>setPage(v=>v-1)} style={[s.pageButton,page===1&&s.disabled]}><Text>‹</Text></Pressable><Text style={s.pageText}>{page}/{totalPages}</Text><Pressable disabled={page===totalPages} onPress={()=>setPage(v=>v+1)} style={[s.pageButton,page===totalPages&&s.disabled]}><Text>›</Text></Pressable></View>}</ScrollView></SafeAreaView>}
function Filter({label,value,onPress}:{label:string;value:string;onPress:()=>void}){return <Pressable style={s.field} onPress={onPress}><Text style={s.fieldLabel}>{label}</Text><Text numberOfLines={1} style={s.fieldValue}>{value}　⌄</Text></Pressable>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{paddingHorizontal:Spacing.lg,paddingBottom:30},eyebrow:{fontFamily:FontFamily.bodySemiBold,fontSize:10,color:Colors.primary,marginTop:12},title:{fontFamily:FontFamily.display,fontSize:29,lineHeight:36,color:Colors.text,marginTop:8},subtitle:{fontFamily:FontFamily.body,fontSize:13,lineHeight:20,color:Colors.textSecondary,marginTop:6},stats:{flexDirection:'row',gap:10,marginTop:20},stat:{flex:1,backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,alignItems:'center',paddingVertical:13,...Shadow},statValue:{fontFamily:FontFamily.bodyBold,fontSize:17,color:Colors.primary},statLabel:{fontFamily:FontFamily.body,fontSize:9,color:Colors.textMuted,marginTop:4},filterCard:{backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.lg,padding:14,marginTop:16,...Shadow},searchInput:{height:45,flexDirection:'row',alignItems:'center',gap:8,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,paddingHorizontal:12,marginBottom:10},input:{flex:1,fontFamily:FontFamily.body,fontSize:12,color:Colors.text},filterRow:{flexDirection:'row',gap:8},field:{flex:1},fieldLabel:{fontFamily:FontFamily.bodySemiBold,fontSize:8,color:Colors.textMuted,marginBottom:5},fieldValue:{fontFamily:FontFamily.body,fontSize:11,color:Colors.text,backgroundColor:Colors.background,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.sm,padding:10},searchButton:{height:44,borderRadius:Radius.md,backgroundColor:Colors.primary,flexDirection:'row',gap:8,alignItems:'center',justifyContent:'center',marginTop:12},searchText:{fontFamily:FontFamily.bodySemiBold,fontSize:13,color:Colors.white},chips:{gap:8,paddingVertical:18},chip:{borderWidth:1,borderColor:Colors.border,borderRadius:Radius.pill,paddingHorizontal:16,paddingVertical:10,backgroundColor:Colors.surface},chipActive:{backgroundColor:Colors.primary,borderColor:Colors.primary},chipText:{fontFamily:FontFamily.bodyMedium,fontSize:12,color:Colors.textSecondary},chipTextActive:{color:Colors.white},listHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:14},result:{fontFamily:FontFamily.display,fontSize:17,color:Colors.text},sort:{borderWidth:1,borderColor:Colors.border,borderRadius:Radius.sm,paddingHorizontal:10,paddingVertical:7},sortText:{fontFamily:FontFamily.body,fontSize:10,color:Colors.textSecondary},grid:{flexDirection:'row',flexWrap:'wrap',gap:12},pagination:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:16,marginTop:24},pageButton:{width:38,height:38,borderRadius:99,backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,alignItems:'center',justifyContent:'center'},disabled:{opacity:.35},pageText:{fontFamily:FontFamily.bodySemiBold,color:Colors.primary}});
