import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import * as ImagePicker from 'expo-image-picker';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { chatApi } from '@/apis/chatApi';
import { RequireAuth } from '@/components/auth/RequireAuth';
import { LoadingState } from '@/components/ui/ScreenState';
import { Colors, FontFamily, Radius } from '@/constants/theme';
import { useAuth } from '@/contexts/AuthContext';
import { useSocket } from '@/contexts/SocketContext';
import { useToast } from '@/contexts/ToastContext';
import type { ChatMessage } from '@/types/chat';
import { getApiErrorMessage } from '@/utils/apiError';
import { getMediaUrl } from '@/utils/media';

export default function Screen(){return <RequireAuth><Conversation/></RequireAuth>}
function Conversation(){
  const{id,name='Đối tác'}=useLocalSearchParams<{id:string;name?:string}>();const{user}=useAuth();const{socket,isConnected}=useSocket();const{show}=useToast();const[messages,setMessages]=useState<ChatMessage[]>([]);const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);const[uploading,setUploading]=useState(false);const[text,setText]=useState('');const[attachments,setAttachments]=useState<string[]>([]);const scroll=useRef<ScrollView>(null);
  const load=useCallback(async(silent=false)=>{try{const data=await chatApi.messages(id);setMessages(current=>mergeMessages(current,Array.isArray(data)?data:[]))}catch(e){if(!silent)show(getApiErrorMessage(e,'Không thể tải hội thoại'),'error')}finally{if(!silent)setLoading(false)}},[id,show]);
  useEffect(()=>{void load()},[load]);
  useEffect(()=>{if(isConnected)return;const timer=setInterval(()=>void load(true),5000);return()=>clearInterval(timer)},[isConnected,load]);
  useEffect(()=>{if(!socket||!isConnected)return;socket.emit('join_room',{roomId:id});socket.emit('mark_read',{roomId:id});const onMessage=(message:ChatMessage)=>{if(String(message.roomId)!==id)return;setMessages(current=>mergeMessages(current,[message]));if(String(message.senderId)!==user?.id)socket.emit('mark_read',{roomId:id})};const onRead=(payload:{roomId:string;userId:string})=>{if(String(payload.roomId)!==id||String(payload.userId)===user?.id)return;setMessages(current=>current.map(message=>String(message.senderId)===user?.id?{...message,isRead:true}:message))};socket.on('new_message',onMessage);socket.on('messages_read',onRead);return()=>{socket.off('new_message',onMessage);socket.off('messages_read',onRead)}},[socket,isConnected,id,user?.id]);
  useEffect(()=>{const timer=setTimeout(()=>scroll.current?.scrollToEnd({animated:true}),50);return()=>clearTimeout(timer)},[messages.length]);
  const pick=async()=>{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){show('Cần quyền truy cập thư viện ảnh','error');return}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsMultipleSelection:true,selectionLimit:Math.max(1,5-attachments.length),quality:.8});if(result.canceled)return;setUploading(true);try{const urls:string[]=[];for(const asset of result.assets.slice(0,5-attachments.length)){const body=new FormData();body.append('file',asset.file??({uri:asset.uri,name:asset.fileName??`chat-${Date.now()}.jpg`,type:asset.mimeType??'image/jpeg'} as unknown as Blob));const uploaded=await chatApi.upload(body);urls.push(uploaded.url)}setAttachments(current=>[...current,...urls].slice(0,5))}catch(e){show(getApiErrorMessage(e,'Không thể tải ảnh trò chuyện'),'error')}finally{setUploading(false)}};
  const send=async()=>{const value=text.trim();if((!value&&!attachments.length)||sending||uploading)return;const pending=[...attachments];setText('');setAttachments([]);if(socket&&isConnected){socket.emit('send_message',{roomId:id,messageText:value,attachments:pending});return}setSending(true);try{const message=await chatApi.send(id,value,pending);setMessages(current=>mergeMessages(current,[message]))}catch(e){setText(value);setAttachments(pending);show(getApiErrorMessage(e,'Không thể gửi tin nhắn'),'error')}finally{setSending(false)}};
  if(loading)return <LoadingState label="Đang tải hội thoại..."/>;return <SafeAreaView style={s.safe} edges={['top','bottom']}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.round}><Ionicons name="chevron-back" size={22}/></Pressable><View style={{flex:1}}><Text style={s.name}>{name}</Text><View style={s.connection}><View style={[s.dot,isConnected?s.online:s.offline]}/><Text style={s.sub}>{isConnected?'Realtime đang kết nối':'Đang dùng REST · tự thử lại mỗi 5 giây'}</Text></View></View></View><ScrollView ref={scroll} contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled">{messages.length===0?<Text style={s.empty}>Hãy gửi lời nhắn đầu tiên.</Text>:messages.map((message,index)=>{const mine=String(message.senderId)===user?.id;const isLastMine=mine&&!messages.slice(index+1).some(item=>String(item.senderId)===user?.id);return <View key={message._id} style={[s.bubble,mine?s.mine:s.theirs]}>{message.messageText?<Text style={[s.message,mine&&s.mineText]}>{message.messageText}</Text>:null}{message.attachments?.length?<View style={s.messageImages}>{message.attachments.map((uri,value)=><Image key={`${uri}-${value}`} source={getMediaUrl(uri)} style={s.messageImage} contentFit="cover"/>)}</View>:null}<Text style={[s.time,mine&&s.mineTime]}>{new Date(message.createdAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}{isLastMine&&message.isRead?' · Đã đọc':''}</Text></View>})}</ScrollView>{attachments.length?<ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.previews}>{attachments.map((uri,index)=><View key={`${uri}-${index}`}><Image source={getMediaUrl(uri)} style={s.preview} contentFit="cover"/><Pressable onPress={()=>setAttachments(current=>current.filter((_,value)=>value!==index))} style={s.remove}><Ionicons name="close" size={13} color={Colors.white}/></Pressable></View>)}</ScrollView>:null}<View style={s.composer}><Pressable disabled={uploading||attachments.length>=5} onPress={()=>void pick()} style={[s.attach,(uploading||attachments.length>=5)&&s.disabled]}><Ionicons name={uploading?'cloud-upload-outline':'image-outline'} size={20} color={Colors.primary}/></Pressable><TextInput value={text} onChangeText={setText} onSubmitEditing={()=>void send()} returnKeyType="send" multiline placeholder={uploading?'Đang tải ảnh...':'Nhập tin nhắn...'} placeholderTextColor={Colors.textMuted} style={s.input}/><Pressable disabled={(!text.trim()&&!attachments.length)||sending||uploading} onPress={()=>void send()} style={[s.send,((!text.trim()&&!attachments.length)||sending||uploading)&&s.disabled]}><Ionicons name="send" size={18} color={Colors.white}/></Pressable></View></KeyboardAvoidingView></SafeAreaView>;
}
function mergeMessages(current:ChatMessage[],incoming:ChatMessage[]){const byId=new Map<string,ChatMessage>();[...current,...incoming].forEach(message=>byId.set(String(message._id),message));return [...byId.values()].sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime())}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},header:{height:62,paddingHorizontal:14,borderBottomWidth:1,borderBottomColor:Colors.border,backgroundColor:Colors.surface,flexDirection:'row',alignItems:'center',gap:11},round:{width:38,height:38,borderRadius:99,alignItems:'center',justifyContent:'center'},name:{fontFamily:FontFamily.bodyBold,fontSize:14,color:Colors.text},connection:{flexDirection:'row',alignItems:'center',gap:5,marginTop:3},dot:{width:6,height:6,borderRadius:99},online:{backgroundColor:Colors.success},offline:{backgroundColor:Colors.warning},sub:{fontFamily:FontFamily.body,fontSize:9,color:Colors.textMuted},messages:{padding:14,gap:8,flexGrow:1,justifyContent:'flex-end'},empty:{fontFamily:FontFamily.body,fontSize:11,color:Colors.textMuted,textAlign:'center',marginVertical:30},bubble:{maxWidth:'82%',paddingHorizontal:10,paddingVertical:9,borderRadius:Radius.md},mine:{alignSelf:'flex-end',backgroundColor:Colors.primary,borderBottomRightRadius:3},theirs:{alignSelf:'flex-start',backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,borderBottomLeftRadius:3},message:{fontFamily:FontFamily.body,fontSize:12,lineHeight:18,color:Colors.text,paddingHorizontal:3},mineText:{color:Colors.white},messageImages:{flexDirection:'row',flexWrap:'wrap',gap:5,marginTop:4},messageImage:{width:120,height:110,borderRadius:Radius.sm,backgroundColor:Colors.surfaceSoft},time:{fontFamily:FontFamily.body,fontSize:7,color:Colors.textMuted,marginTop:5,paddingHorizontal:3},mineTime:{color:'#E9C9CF',textAlign:'right'},previews:{gap:8,paddingHorizontal:12,paddingVertical:8,backgroundColor:Colors.surface,borderTopWidth:1,borderTopColor:Colors.border},preview:{width:64,height:64,borderRadius:Radius.sm,backgroundColor:Colors.surfaceSoft},remove:{position:'absolute',right:-4,top:-4,width:20,height:20,borderRadius:10,backgroundColor:Colors.error,alignItems:'center',justifyContent:'center'},composer:{padding:10,borderTopWidth:1,borderTopColor:Colors.border,backgroundColor:Colors.surface,flexDirection:'row',alignItems:'flex-end',gap:8},attach:{width:44,height:44,borderRadius:Radius.md,borderWidth:1,borderColor:Colors.border,alignItems:'center',justifyContent:'center'},input:{flex:1,maxHeight:100,minHeight:44,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,paddingHorizontal:12,paddingVertical:10,fontFamily:FontFamily.body,fontSize:11,color:Colors.text},send:{width:44,height:44,borderRadius:Radius.md,backgroundColor:Colors.primary,alignItems:'center',justifyContent:'center'},disabled:{opacity:.4}});
