import { Ionicons } from '@expo/vector-icons';
import { router, useLocalSearchParams } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { chatApi } from '@/apis/chatApi';
import { RequireAuth } from '@/components/auth/RequireAuth';
import { LoadingState } from '@/components/ui/ScreenState';
import { Colors, FontFamily, Radius } from '@/constants/theme';
import { useAuth } from '@/contexts/AuthContext';
import { useToast } from '@/contexts/ToastContext';
import type { ChatMessage } from '@/types/chat';
import { getApiErrorMessage } from '@/utils/apiError';

export default function Screen(){return <RequireAuth><Conversation/></RequireAuth>}
function Conversation(){const{id,name='Đối tác'}=useLocalSearchParams<{id:string;name?:string}>();const{user}=useAuth();const{show}=useToast();const[messages,setMessages]=useState<ChatMessage[]>([]);const[loading,setLoading]=useState(true);const[sending,setSending]=useState(false);const[text,setText]=useState('');const scroll=useRef<ScrollView>(null);
  const load=useCallback(async(silent=false)=>{try{const data=await chatApi.messages(id);setMessages(Array.isArray(data)?data:[])}catch(e){if(!silent)show(getApiErrorMessage(e,'Không thể tải hội thoại'),'error')}finally{if(!silent)setLoading(false)}},[id,show]);
  useEffect(()=>{void load();const timer=setInterval(()=>void load(true),5000);return()=>clearInterval(timer)},[load]);useEffect(()=>{setTimeout(()=>scroll.current?.scrollToEnd({animated:true}),50)},[messages.length]);
  const send=async()=>{const value=text.trim();if(!value||sending)return;setText('');setSending(true);try{const message=await chatApi.send(id,value);setMessages(current=>current.some(item=>item._id===message._id)?current:[...current,message])}catch(e){setText(value);show(getApiErrorMessage(e,'Không thể gửi tin nhắn'),'error')}finally{setSending(false)}};
  if(loading)return <LoadingState label="Đang tải hội thoại..."/>;return <SafeAreaView style={s.safe} edges={['top','bottom']}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.round}><Ionicons name="chevron-back" size={22}/></Pressable><View style={{flex:1}}><Text style={s.name}>{name}</Text><Text style={s.sub}>Đối tác LUMÉ · tự làm mới 5 giây</Text></View></View><ScrollView ref={scroll} contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled">{messages.length===0?<Text style={s.empty}>Hãy gửi lời nhắn đầu tiên.</Text>:messages.map(message=>{const mine=String(message.senderId)===user?.id;return <View key={message._id} style={[s.bubble,mine?s.mine:s.theirs]}><Text style={[s.message,mine&&s.mineText]}>{message.messageText}</Text><Text style={[s.time,mine&&s.mineTime]}>{new Date(message.createdAt).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</Text></View>})}</ScrollView><View style={s.composer}><TextInput value={text} onChangeText={setText} onSubmitEditing={()=>void send()} returnKeyType="send" multiline placeholder="Nhập tin nhắn..." placeholderTextColor={Colors.textMuted} style={s.input}/><Pressable disabled={!text.trim()||sending} onPress={()=>void send()} style={[s.send,(!text.trim()||sending)&&{opacity:.4}]}><Ionicons name="send" size={18} color={Colors.white}/></Pressable></View></KeyboardAvoidingView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},header:{height:62,paddingHorizontal:14,borderBottomWidth:1,borderBottomColor:Colors.border,backgroundColor:Colors.surface,flexDirection:'row',alignItems:'center',gap:11},round:{width:38,height:38,borderRadius:99,alignItems:'center',justifyContent:'center'},name:{fontFamily:FontFamily.bodyBold,fontSize:14,color:Colors.text},sub:{fontFamily:FontFamily.body,fontSize:9,color:Colors.textMuted,marginTop:2},messages:{padding:14,gap:8,flexGrow:1,justifyContent:'flex-end'},empty:{fontFamily:FontFamily.body,fontSize:11,color:Colors.textMuted,textAlign:'center',marginVertical:30},bubble:{maxWidth:'80%',paddingHorizontal:13,paddingVertical:9,borderRadius:Radius.md},mine:{alignSelf:'flex-end',backgroundColor:Colors.primary,borderBottomRightRadius:3},theirs:{alignSelf:'flex-start',backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,borderBottomLeftRadius:3},message:{fontFamily:FontFamily.body,fontSize:12,lineHeight:18,color:Colors.text},mineText:{color:Colors.white},time:{fontFamily:FontFamily.body,fontSize:7,color:Colors.textMuted,marginTop:4},mineTime:{color:'#E9C9CF',textAlign:'right'},composer:{padding:10,borderTopWidth:1,borderTopColor:Colors.border,backgroundColor:Colors.surface,flexDirection:'row',alignItems:'flex-end',gap:8},input:{flex:1,maxHeight:100,minHeight:44,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,paddingHorizontal:12,paddingVertical:10,fontFamily:FontFamily.body,fontSize:11,color:Colors.text},send:{width:44,height:44,borderRadius:Radius.md,backgroundColor:Colors.primary,alignItems:'center',justifyContent:'center'}});
