import { Ionicons } from '@expo/vector-icons';
import { Image } from 'expo-image';
import { type Href, router, useFocusEffect } from 'expo-router';
import { useCallback, useMemo, useState } from 'react';
import { Pressable, RefreshControl, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { chatApi } from '@/apis/chatApi';
import { RequireAuth } from '@/components/auth/RequireAuth';
import { EmptyState, ErrorState, LoadingState } from '@/components/ui/ScreenState';
import { Colors, FontFamily, Radius, Shadow } from '@/constants/theme';
import type { ChatRoom } from '@/types/chat';
import { getApiErrorMessage } from '@/utils/apiError';
import { getMediaUrl } from '@/utils/media';

export default function Screen(){return <RequireAuth><Rooms/></RequireAuth>}
function Rooms(){const[rooms,setRooms]=useState<ChatRoom[]>([]);const[loading,setLoading]=useState(true);const[refreshing,setRefreshing]=useState(false);const[error,setError]=useState<string|null>(null);const[q,setQ]=useState('');const load=useCallback(async(silent=false)=>{silent?setRefreshing(true):setLoading(true);try{setError(null);const data=await chatApi.rooms();setRooms(Array.isArray(data)?data:[])}catch(e){setError(getApiErrorMessage(e,'Không thể tải tin nhắn'))}finally{setLoading(false);setRefreshing(false)}},[]);useFocusEffect(useCallback(()=>{void load();return undefined},[load]));const filtered=useMemo(()=>rooms.filter(room=>!q||`${room.otherParticipant?.fullName??''} ${room.lastMessage?.messageText??''}`.toLowerCase().includes(q.toLowerCase())),[rooms,q]);if(loading)return <LoadingState label="Đang tải hội thoại..."/>;return <SafeAreaView style={s.safe} edges={['top']}><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load(true)} tintColor={Colors.primary}/>} contentContainerStyle={s.content}><View style={s.header}><Pressable onPress={()=>router.back()} style={s.round}><Ionicons name="chevron-back" size={22}/></Pressable><View style={{flex:1}}><Text style={s.title}>Tin nhắn</Text><Text style={s.sub}>Trao đổi với cửa hàng và photographer</Text></View></View><View style={s.search}><Ionicons name="search" size={18} color={Colors.textMuted}/><TextInput value={q} onChangeText={setQ} placeholder="Tìm người hoặc nội dung..." placeholderTextColor={Colors.textMuted} style={s.input}/></View>{error?<ErrorState message={error} onRetry={()=>void load()}/>:filtered.length===0?<EmptyState title="Chưa có hội thoại" message="Hội thoại với đơn vị cung cấp sẽ xuất hiện tại đây."/>:<View style={s.list}>{filtered.map(room=><RoomCard key={room.id} room={room}/>)}</View>}</ScrollView></SafeAreaView>}
function RoomCard({room}:{room:ChatRoom}){const partner=room.otherParticipant;return <Pressable onPress={()=>router.push({pathname:'/chat/[id]',params:{id:room.id,name:partner?.fullName??'Đối tác'}} as unknown as Href)} style={s.card}>{partner?.avatarUrl?<Image source={getMediaUrl(partner.avatarUrl)} style={s.avatar}/>:<View style={s.avatar}><Text style={s.initial}>{(partner?.fullName??'L').charAt(0)}</Text></View>}<View style={{flex:1}}><View style={s.cardTop}><Text style={s.name}>{partner?.fullName??'Đối tác LUMÉ'}</Text><Text style={s.time}>{time(room.lastMessageAt)}</Text></View><Text numberOfLines={1} style={s.preview}>{room.lastMessage?.messageText||'Bắt đầu trò chuyện'}</Text></View></Pressable>}
const time=(value:string|null)=>value?new Date(value).toLocaleDateString('vi-VN',{day:'2-digit',month:'2-digit'}):'';
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{padding:16,paddingBottom:38,gap:15},header:{flexDirection:'row',alignItems:'center',gap:12},round:{width:40,height:40,borderRadius:99,borderWidth:1,borderColor:Colors.border,alignItems:'center',justifyContent:'center'},title:{fontFamily:FontFamily.display,fontSize:25,color:Colors.text},sub:{fontFamily:FontFamily.body,fontSize:10,color:Colors.textMuted,marginTop:3},search:{height:49,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.md,backgroundColor:Colors.surface,flexDirection:'row',alignItems:'center',gap:8,paddingHorizontal:13,...Shadow},input:{flex:1,fontFamily:FontFamily.body,fontSize:11,color:Colors.text},list:{gap:9},card:{padding:13,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.lg,backgroundColor:Colors.surface,flexDirection:'row',alignItems:'center',gap:11,...Shadow},avatar:{width:48,height:48,borderRadius:99,backgroundColor:Colors.primarySoft,alignItems:'center',justifyContent:'center'},initial:{fontFamily:FontFamily.display,fontSize:18,color:Colors.primary},cardTop:{flexDirection:'row',justifyContent:'space-between',gap:8},name:{fontFamily:FontFamily.bodyBold,fontSize:12,color:Colors.text},time:{fontFamily:FontFamily.body,fontSize:8,color:Colors.textMuted},preview:{fontFamily:FontFamily.body,fontSize:10,color:Colors.textMuted,marginTop:6}});
