export const PolicyErrorCode = {
  NotFound: 'SYSTEM_POLICY_NOT_FOUND',
  CodeTypeMismatch: 'SYSTEM_POLICY_CODE_TYPE_MISMATCH',
  ValueInvalid: 'SYSTEM_POLICY_VALUE_INVALID',
  ActiveCannotBeUpdated: 'SYSTEM_POLICY_ACTIVE_CANNOT_BE_UPDATED',
  ReasonRequired: 'SYSTEM_POLICY_REASON_REQUIRED',
  VersionConflict: 'SYSTEM_POLICY_VERSION_CONFLICT',
  ActivateStatusInvalid: 'SYSTEM_POLICY_ACTIVATE_STATUS_INVALID',
  ActivateFailed: 'SYSTEM_POLICY_ACTIVATE_FAILED',
  ConcurrentActivation: 'SYSTEM_POLICY_CONCURRENT_ACTIVATION',
  LastActiveCannotBeDeactivated:
    'SYSTEM_POLICY_LAST_ACTIVE_CANNOT_BE_DEACTIVATED',
  ImmutableField: 'SYSTEM_POLICY_IMMUTABLE_FIELD',
  InvalidId: 'SYSTEM_POLICY_ID_INVALID',
} as const;
