import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { bookingApi } from '@/apis/bookingApi';
import { AppButton } from '@/components/ui/AppButton';
import { AppInput } from '@/components/ui/AppInput';
import { AppModal } from '@/components/ui/AppModal';
import { Colors, FontFamily, Radius, Spacing } from '@/constants/theme';
import { useToast } from '@/contexts/ToastContext';
import type { Booking, BookingItem } from '@/types/booking';
import { getApiErrorMessage } from '@/utils/apiError';

const toMinutes=(value:string)=>{const[hours,minutes]=value.trim().split(':').map(Number);return Number.isFinite(hours)&&Number.isFinite(minutes)?hours*60+minutes:NaN};
const toTime=(minutes:number)=>`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`;
const overlaps=(first:string,second:string)=>{const[a,b]=first.split('-').map(toMinutes);const[c,d]=second.split('-').map(toMinutes);return[a,b,c,d].every(Number.isFinite)&&a<d&&c<b};
const dateOnly=(value?:string|null)=>value?String(value).slice(0,10):'';

interface Props { visible:boolean; booking:Booking; item:BookingItem|null; onClose:()=>void; onSuccess:()=>Promise<void>|void; }

export function RescheduleModal({visible,booking,item,onClose,onSuccess}:Props){
  const{show}=useToast();
  const[from,setFrom]=useState('');const[to,setTo]=useState('');const[shootDate,setShootDate]=useState('');const[slot,setSlot]=useState('');const[reason,setReason]=useState('');
  const[slots,setSlots]=useState<string[]>([]);const[loadingSlots,setLoadingSlots]=useState(false);const[slotError,setSlotError]=useState<string|null>(null);const[submitting,setSubmitting]=useState(false);
  const isProduct=item?.itemType==='PRODUCT';
  const duration=useMemo(()=>{const pkg=item?.photographyPackageId;const value=Number(item?.packageSnapshot?.includedDurationMinutes||(pkg&&typeof pkg==='object'?(pkg.durationHours??0)*60:0));return Number.isFinite(value)&&value>0?value:120},[item]);
  useEffect(()=>{if(!visible||!item)return;setFrom(dateOnly(item.rentalFrom));setTo(dateOnly(item.rentalTo));setShootDate(dateOnly(item.shootDate));setSlot(item.shootTimeSlot??'');setReason('');setSlotError(null)},[visible,item]);
  useEffect(()=>{if(!visible||isProduct||!item||!shootDate)return;const raw=item.providerId??booking.providerIds?.[0];const providerId=typeof raw==='string'?raw:raw?._id;if(!providerId){setSlotError('Không xác định được nhiếp ảnh gia của lịch này.');setSlots([]);return}let active=true;setLoadingSlots(true);setSlotError(null);setSlot('');Promise.all([bookingApi.providerAvailability(providerId,shootDate),bookingApi.providerBusyDates(providerId)]).then(([availability,busy])=>{if(!active)return;const next=(availability.timeRanges??[]).flatMap(range=>{const start=toMinutes(range.start),end=toMinutes(range.end);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)return[];const candidates:string[]=[];for(let cursor=start;cursor+duration<=end;cursor+=30){const candidate=`${toTime(cursor)}-${toTime(cursor+duration)}`;const conflict=(busy.bookedSlots??[]).some(value=>value.date===shootDate&&value.bookingItemId!==item._id&&overlaps(candidate,value.timeSlot));if(!conflict)candidates.push(candidate)}return candidates});setSlots([...new Set(next)]);if(!next.length)setSlotError('Không còn khung giờ phù hợp trong ngày này.');}).catch(cause=>{if(active){setSlots([]);setSlotError(getApiErrorMessage(cause,'Không thể tải khung giờ trống.'))}}).finally(()=>{if(active)setLoadingSlots(false)});return()=>{active=false}},[visible,isProduct,item,booking.providerIds,shootDate,duration]);
  const submit=async()=>{if(!item)return;if(isProduct&&(!from||!to)){show('Vui lòng nhập ngày nhận và ngày trả mới','error');return}if(isProduct&&to<from){show('Ngày trả phải sau ngày nhận','error');return}if(!isProduct&&(!shootDate||!slot)){show('Vui lòng chọn ngày và khung giờ mới','error');return}setSubmitting(true);try{const response=await bookingApi.reschedule(booking._id,{itemId:item._id,...(isProduct?{newRentalFrom:from,newRentalTo:to}:{newShootDate:shootDate,newShootTimeSlot:slot}),reason:reason.trim()||undefined});show(response.directUpdate||response.status==='APPROVED'?'Lịch mới đã được cập nhật':'Đã gửi yêu cầu đổi lịch, vui lòng chờ xác nhận','success');onClose();await onSuccess()}catch(cause){show(getApiErrorMessage(cause,'Không thể đổi lịch.'),'error')}finally{setSubmitting(false)}};
  return <AppModal visible={visible} title="Đổi lịch dịch vụ" onClose={onClose}><ScrollView style={styles.scroll} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.notice}>Yêu cầu cần gửi trước ít nhất 24 giờ. Lịch mới chỉ có hiệu lực sau khi được xác nhận.</Text>{isProduct?<><AppInput label="NGÀY NHẬN MỚI (YYYY-MM-DD)" value={from} onChangeText={setFrom} placeholder="2026-08-20" autoCapitalize="none"/><AppInput label="NGÀY TRẢ MỚI (YYYY-MM-DD)" value={to} onChangeText={setTo} placeholder="2026-08-23" autoCapitalize="none"/></>:<><AppInput label="NGÀY CHỤP MỚI (YYYY-MM-DD)" value={shootDate} onChangeText={setShootDate} placeholder="2026-08-20" autoCapitalize="none"/>{loadingSlots?<ActivityIndicator color={Colors.primary}/>:slotError?<Text style={styles.error}>{slotError}</Text>:<View style={styles.slots}>{slots.map(value=><Pressable key={value} onPress={()=>setSlot(value)} style={[styles.slot,slot===value&&styles.slotActive]}><Text style={[styles.slotText,slot===value&&styles.slotTextActive]}>{value.replace('-',' – ')}</Text></Pressable>)}</View>}</>}<AppInput label="LÝ DO (TÙY CHỌN)" value={reason} onChangeText={setReason} multiline maxLength={500} placeholder="Nhập lý do đổi lịch..." style={styles.reason}/><AppButton title="Gửi yêu cầu đổi lịch" loading={submitting} onPress={()=>void submit()}/></ScrollView></AppModal>;
}

const styles=StyleSheet.create({scroll:{maxHeight:560},content:{gap:Spacing.md,paddingBottom:Spacing.sm},notice:{fontFamily:FontFamily.body,fontSize:10,lineHeight:16,color:Colors.warning,backgroundColor:Colors.warningSoft,padding:12,borderRadius:Radius.sm},slots:{flexDirection:'row',flexWrap:'wrap',gap:8},slot:{paddingVertical:9,paddingHorizontal:12,borderWidth:1,borderColor:Colors.border,borderRadius:Radius.sm,backgroundColor:Colors.surface},slotActive:{backgroundColor:Colors.primary,borderColor:Colors.primary},slotText:{fontFamily:FontFamily.bodySemiBold,fontSize:10,color:Colors.text},slotTextActive:{color:Colors.white},error:{fontFamily:FontFamily.body,fontSize:10,lineHeight:15,color:Colors.error},reason:{minHeight:76,textAlignVertical:'top'}});
