export const ROUTES = {
  LANDING: '/',
  RENTALS: '/rentals',
  PHOTOGRAPHERS: '/photographers',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  VERIFY_EMAIL: '/auth/verify-email',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  PROFILE: '/dashboard/profile',
  SETTINGS: '/dashboard/settings',
  PROVIDER_DASHBOARD: '/provider/dashboard',
  PROVIDER_REGISTER: '/provider/register',
  OAUTH_CALLBACK: '/oauth/callback',
  PRODUCT_DETAIL: '/rentals/:id',
  PHOTOGRAPHER_DETAIL: '/photographers/:id',
  CART: '/cart',
  CHECKOUT_RESULT: '/checkout/result',
  ADMIN_DASHBOARD: '/admin/dashboard',
  ADMIN_DASHBOARD_REFACTORED: '/admin/dashboard-refactored',
  COMBOS: '/combos',
  COMBO_DETAIL: '/combos/:id',
  PROVIDER_STORE: '/stores/:id',
  NOTIFICATIONS: '/notifications',
  CHAT: '/chat',
} as const;
// Touch to reload.
