export const ROUTES = {
  LANDING: '/',
  RENTALS: '/rentals',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  VERIFY_EMAIL: '/auth/verify-email',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  PROFILE: '/dashboard/profile',
  SETTINGS: '/dashboard/settings',
  PROVIDER_DASHBOARD: '/provider/dashboard',
  OAUTH_CALLBACK: '/oauth/callback',
} as const;
