import { Ionicons } from '@expo/vector-icons';
import { router } from 'expo-router';
import type { ReactNode } from 'react';
import { KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Colors,FontFamily } from '@/constants/theme';

export function AuthFrame({children}:{children:ReactNode}){return <SafeAreaView style={s.safe}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Pressable style={s.close} onPress={()=>router.canGoBack()?router.back():router.replace('/')}><Ionicons name="chevron-back" size={22} color={Colors.text}/></Pressable><View style={s.brandWrap}><View style={s.mark}><Text style={s.markText}>L</Text></View><Text style={s.brand}>LUMÉ</Text><Text style={s.tagline}>ÁO DÀI & CHỤP ẢNH</Text></View>{children}</ScrollView></KeyboardAvoidingView></SafeAreaView>}
export const authStyles=StyleSheet.create({card:{width:'100%',maxWidth:480,alignSelf:'center',backgroundColor:Colors.surface,borderWidth:1,borderColor:Colors.border,borderRadius:22,padding:20,gap:15},eyebrow:{fontFamily:FontFamily.bodyBold,fontSize:9,color:Colors.primary},title:{fontFamily:FontFamily.display,fontSize:29,color:Colors.text,marginTop:-6},subtitle:{fontFamily:FontFamily.body,fontSize:11,lineHeight:18,color:Colors.textSecondary,marginTop:-7,marginBottom:3},error:{fontFamily:FontFamily.bodyMedium,fontSize:10,lineHeight:16,color:Colors.error,backgroundColor:Colors.errorSoft,padding:10,borderRadius:8},success:{fontFamily:FontFamily.bodyMedium,fontSize:10,lineHeight:16,color:Colors.success,backgroundColor:Colors.successSoft,padding:10,borderRadius:8},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:8},link:{fontFamily:FontFamily.bodySemiBold,fontSize:10,color:Colors.primary},help:{fontFamily:FontFamily.body,fontSize:9,lineHeight:15,color:Colors.textMuted,textAlign:'center'}});
const s=StyleSheet.create({safe:{flex:1,backgroundColor:Colors.background},content:{flexGrow:1,padding:20,justifyContent:'center'},close:{position:'absolute',top:14,left:16,width:40,height:40,borderRadius:99,borderWidth:1,borderColor:Colors.border,backgroundColor:Colors.surface,alignItems:'center',justifyContent:'center'},brandWrap:{alignItems:'center',marginBottom:24},mark:{width:52,height:52,borderRadius:99,backgroundColor:Colors.primary,alignItems:'center',justifyContent:'center'},markText:{fontFamily:FontFamily.display,fontSize:22,color:Colors.white},brand:{fontFamily:FontFamily.display,fontSize:23,letterSpacing:6,color:Colors.primary,marginTop:10},tagline:{fontFamily:FontFamily.bodyMedium,fontSize:8,letterSpacing:1.5,color:Colors.textMuted,marginTop:3}});
